### PR TITLE
Glowing apple logo

### PR DESCRIPTION
**Pull request by abhijeet-26**
#245

### CODE REVIEW

**Review by Vanshiii203 — CHANGES_REQUESTED** [review]
Please link the issue with the PR and attach the screenshot of project in readme not the screen recording

**Comment by abhijeet-26** [comment]
Please check and let me know

**Review by Vanshiii203 — APPROVED** [review]
LGTM!

**Comment by Vanshiii203** [comment]
> Please check and let me know
From now on, you should raise the issue first before making PRs.

**Comment by TusharKesarwani** [comment]
You have to make something creative 
This type of project is not accepted

**Pull request closed without merging**
