### PR TITLE
Tip calculator

### PR DESCRIPTION
**Pull request by patnaikankit**
## 🛠️ Issue (1033)

Closes # 1033

# Description

The application will calculate the total amount to be paid, including the tip, based on the bill amount and the tip percentage entered by the user.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] The title of my pull request is a short description of the requested changes.

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Comment by patnaikankit** [comment]
@TusharKesarwani @Arun9739 @harshit-paneri please go through this pr and give your feedback. I have implemented a tip calculator in this pr.

**Review by Arun9739 — CHANGES_REQUESTED** [review]
@patnaikankit mention issue number

**Comment by patnaikankit** [comment]
@Arun9739 I have added the issue number to the pull request.

**Comment by Arun9739** [comment]
@patnaikankit What i sumon game? How it is related to your issue?

**Comment by patnaikankit** [comment]
@Arun9739 I have deleted the Simon game which was from a previous issue. In the latest commit, you will only find the tip calculator.

**Review by Arun9739 — APPROVED** [review]

**Comment by TusharKesarwani** [comment]
You should write as Closes #1033

**Review by TusharKesarwani — APPROVED** [review]

**Pull request merged**
