### PR TITLE
DSA solver webpages(solve issue #922)

### LINKED ISSUE #922: I want make DSA solver webpage using html,css,js
## **Describe the project**
A clear and concise description of the project you are going to add to this repository.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

### PR DESCRIPTION
**Pull request by princekumarg**
## 🛠️ Issue (#922 )

Closes #922 

# Description

I Had Made a DSA Solver WEBpages using html , css , js.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] The title of my pull request is a short description of the requested changes.

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
Screenshot 2023-06-20 001525
Screenshot 2023-06-20 001654

### CODE REVIEW

**Comment by princekumarg** [comment]
Please Check The updated Branch is correct or Not.i had Solve The issue(#922)

**Comment by zugzwang03** [comment]
update the branch

**Comment by princekumarg** [comment]
@zugzwang03 what would be the branch name

**Comment by princekumarg** [comment]
@zugzwang03 what types of Changes i have to made.

**Comment by zugzwang03** [comment]
you have to make your branch up to date, that is in sync with the present repo version.

**Comment by zugzwang03** [comment]
image

**Comment by princekumarg** [comment]
Okk

**Comment by princekumarg** [comment]
Screenshot 2023-06-23 154701

@zugzwang03 I had Make Every-thing update but still.showing behind

**Comment by princekumarg** [comment]
Screenshot 2023-06-23 154919
it Still doesn't show uptodate

**Comment by princekumarg** [comment]
Screenshot 2023-06-24 112016

**Comment by princekumarg** [comment]
@zugzwang03 Please merge this issue.i had updated my branch

**Comment by zugzwang03** [comment]
there is some issue with the deployment

**Comment by zugzwang03** [comment]
did you add your project to the cards?

**Comment by princekumarg** [comment]
I don't know about any project card please help me.

**Comment by princekumarg** [comment]
Screenshot 2023-06-25 115915

**Review by zugzwang03 — APPROVED** [review]

**Review by TusharKesarwani — APPROVED** [review]

**Pull request merged**
