### PR TITLE
Home Page of Newletter Website

### LINKED ISSUE #838: Home Page of Newsletter Website
## **Describe the project**
I want to create homepage of newsletter website.
It will display some news content and many other facilities on that homepage.
That will be only front-end part. 
I will use HTML, CSS & JavaScript in this project. I will complete this project with great UI/UX by adding required styles and animation in it.

## Issue Type:
- [x] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

### PR DESCRIPTION
**Pull request by SomilRathore01**
## 🛠️ #838  

Closes #838 

# Description

I have created the home page of a newsletter website by using HTML & CSS only. In this site I have created a navigation bar on top, some news and after it footer content, subscription form and also used font awesome icons .

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own.
- [x] The title of my pull request is a short description of the requested changes.

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
Screenshot (408)
Screenshot (409)

### CODE REVIEW

**Review by TusharKesarwani — CHANGES_REQUESTED** [review]
Add only one project

**Comment by SomilRathore01** [comment]
> Add only one project

Sorry for that, now I have added only one project please review it again.

**Review by TusharKesarwani — CHANGES_REQUESTED** [review]
Add only one project

**Comment by SomilRathore01** [comment]
Ok I am closing this pr and I will raise new pr with only one project of newsletter website.

**Pull request closed without merging**
