### PR TITLE
Ball Fall Game

### LINKED ISSUE #413: Ball Fall Game
## **Describe the project**
"The ball is lost in the extremeties of space while exploring.If its touches the extreme of space,it will lose it life.Manage to save the ball's life by drawing it towards the bottom and extending its life time....Lets Start!! "

## Issue Type:

- [x] New Project

### PR DESCRIPTION
**Pull request by S-ishita**
Closes #413 

# Description

"The ball is lost in the extremeties of space while exploring.If its touches the extreme of space,it will lose it life.Manage to save the ball's life by drawing it towards the bottom and extending its life time....Lets Start!! "

# Falling_Ball_Game
This folder contains the code of the Falling Ball Game built using HTML,CSS and Javascript language.It can be controlled using onscreen arrow buttons or left and right key on keyboard.

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
 

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

Screenshot from 2023-01-24 17-14-05

### CODE REVIEW

**Review by LiQuiD-404 — CHANGES_REQUESTED** [review]
@S-ishita Kindly add a Readme.md file and add a project description and the tech stack used.

**Comment by S-ishita** [comment]
Done @LiQuiD-404 .Also,kindly ignore the tetris commit.

**Review by Vanshiii203 — CHANGES_REQUESTED** [review]
attach the screenshot of project in readme.md file

**Comment by S-ishita** [comment]
done @Vanshiii203

**Review by Vanshiii203 — APPROVED** [review]
LGTM!

**Review by TusharKesarwani — APPROVED** [review]

**Pull request merged**
