### PR TITLE
changed the UI of Bookmark-App

### PR DESCRIPTION
**Pull request by HimanshiDafouty**
## 🛠️ Issue (#1293)

https://github.com/TusharKesarwani/Front-End-Projects/assets/116953498/df47cc61-21d0-479e-9ef0-b3b9f39115a0

https://github.com/TusharKesarwani/Front-End-Projects/assets/116953498/20c25a52-3399-4c48-b2b3-594a65e2b663

Closes #

# Description

Please include a summary of the change. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [ ] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] The title of my pull request is a short description of the requested changes.

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Review by zugzwang03 — APPROVED** [review]

**Review by TusharKesarwani — CHANGES_REQUESTED** [review]
Not working

**Comment by zugzwang03** [comment]
update your branch @HimanshiDafouty

**Comment by HimanshiDafouty** [comment]
Okay , I will check again.

**Review by zugzwang03 — APPROVED** [review]

**Review by TusharKesarwani — CHANGES_REQUESTED** [review]
Add one project in one PR

**Pull request closed without merging**
