### PR TITLE
Calendar

### PR DESCRIPTION
**Pull request by khushigarg1**
#145 Calendar 
img

### CODE REVIEW

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
There are other files committed such as Armstrong and prime number projects too. See to it.

**Comment by abhilipsasahoo03** [comment]
Hello @khushigarg1 could you please create separate PRs for different projects and not scrunch them all in a single PR? That'd be easy for maintainers to approve your code.

**Comment by khushigarg1** [comment]
> Hello @khushigarg1 could you please create separate PRs for different projects and not scrunch them all in a single PR? That'd be easy for maintainers to approve your code.

Yaa Okay sure i will

**Comment by abhilipsasahoo03** [comment]
> > Hello @khushigarg1 could you please create separate PRs for different projects and not scrunch them all in a single PR? That'd be easy for maintainers to approve your code.
> 
> Yaa Okay sure, this problem is happening because I made 3 prs together.

Also please make sure that for each project you want to submit, create an issue, get yourself assigned by a mentor/maintainer and then create PR for that particular project only.

**Comment by khushigarg1** [comment]
> > > Hello @khushigarg1 could you please create separate PRs for different projects and not scrunch them all in a single PR? That'd be easy for maintainers to approve your code.
> > 
> > 
> > Yaa Okay sure, this problem is happening because I made 3 prs together.
> 
> Also please make sure that for each project you want to submit, create an issue, get yourself assigned by a mentor/maintainer and then create PR for that particular project only.

yess suree i made pr after assigning this to me.

**Comment by khushigarg1** [comment]
Please merge previous pull requests then this problem will get resolve.

**Comment by khushigarg1** [comment]
> @khushigarg1 This PR includes the project for which you have already created a PR (#165). Just add the files of the Calendar project to this PR and delete the files of Armstrong Checker and Prime Checker.

Yes i will just after merging my prime checker project.

**Pull request closed without merging**
