### PR TITLE
Pre-Loader Added #289

### LINKED ISSUE #289: Loading Screen
there is no loading screen redirection to main page i can do that please assign it to me

### PR DESCRIPTION
**Pull request by Shubham185y**
Pre-loader added successfully and working perfectly fine Closes #289

### CODE REVIEW

**Comment by LiQuiD-404** [comment]
@Shubham185y Add a Readme.md file. Also, link your issue with this PR like this: `Closes #Issue Number`.

**Review by LiQuiD-404 — CHANGES_REQUESTED** [review]
Kindly make the necessary changes.

**Comment by Shubham185y** [comment]
where should i add the readme file because i have made the changes in the  main index.html and style.css and created index.js where one readme.md already exist

**Comment by LiQuiD-404** [comment]
@Shubham185y Add some screen recording or screenshot of your project here in the chat.

**Comment by Shubham185y** [comment]
https://user-images.githubusercontent.com/100077254/212980009-95d6dfff-ca73-45bc-b798-5edcf3c3294f.mp4

**Review by Vanshiii203 — CHANGES_REQUESTED** [review]
Resolve merge conflicts

**Review by LiQuiD-404 — APPROVED** [review]
LGTM ✨

**Comment by TusharKesarwani** [comment]
Not working properly

**Comment by Shubham185y** [comment]
just synced it now working properly

**Comment by TusharKesarwani** [comment]
Preloader is already there 
Then why are you adding it again

**Pull request closed without merging**
