### PR TITLE
Added QS-APP project in project folder

### PR DESCRIPTION
**Pull request by helloshiv01**
# Description
Added QS-APP project in project folder.
Quantified Self App is a web based dashboard application used for self­ tracking like tracking habits, daily exercises. It is based on CRUD functionality where users can create multiple trackers and users can log to one more tracker at any time, each time it's logged it will capture TimeStamp, Tracker, Value (based on the corresponding tracker type) and an optional note. Based on the logs in different trackers, the system will track progress over time and show trendlines.
## Type of change- 
- [x] New feature (non-breaking change which adds functionality)
# Checklist:
- [x] I have made this from my own
- [ ] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] The title of my pull request is a short description of the requested changes.
# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
image

### CODE REVIEW

**Comment by Vanshiii203** [comment]
@helloshiv01 Which issue have you resolved?

**Comment by helloshiv01** [comment]
Actually i have added a whole new project to the project folder.

**Comment by helloshiv01** [comment]
It is made in css html and js

**Comment by Vanshiii203** [comment]
> It is made in css html and js
There is a python file in your project folder

**Comment by helloshiv01** [comment]
Any solution?

**Pull request closed without merging**
