### PR TITLE
Adding my project Shortly(an url shortner) using vanilla JS

### PR DESCRIPTION
**Pull request by Diptamoy-Mitra**
This is an URL shortner Application.

### CODE REVIEW

**Review by Vanshiii203 — CHANGES_REQUESTED** [review]
Please link the issue with the PR and in the readme file describe the project and tech stack used

**Comment by Diptamoy-Mitra** [comment]
> Please link the issue with the PR and in the readme file describe the project and tech stack used

yes mam i update my project at readme.md file. Mam please add my project.

**Comment by Vanshiii203** [comment]
This issue is assigned to someone else. You cannot directly raise a PR

**Comment by Diptamoy-Mitra** [comment]
> This issue is assigned to someone else. You cannot directly raise a PR. You can wait for sometime. If the person fails to complete the task, then it will be assigned to you, and then only this PR will be accepted.

all projects are assigned in the list, so what can i do now???

**Comment by TusharKesarwani** [comment]
> > This issue is assigned to someone else. You cannot directly raise a PR. You can wait for sometime. If the person fails to complete the task, then it will be assigned to you, and then only this PR will be accepted.
> 
> all existing issues projects are assigned in the list, so what can i do now???

You can raise unique issues

**Comment by TusharKesarwani** [comment]
> > This issue is assigned to someone else. You cannot directly raise a PR. You can wait for sometime. If the person fails to complete the task, then it will be assigned to you, and then only this PR will be accepted.
> 
> all existing issues projects are assigned in the list, so what can i do now???

Do not work on assigned issues
Create your own unique issues and work on that

**Pull request closed without merging**
