### PR TITLE
Solar website of fixes #54

### LINKED ISSUE #54: Solar Energy Compny Website / Landing Page
**SWOC** S3 Contributor
hey I am working on solar company website made with tailwind css.
Please assign me this.

### PR DESCRIPTION
**Pull request by Saksham-1612**
Please merge this I have done all required edits which fixes #54

### CODE REVIEW

**Comment by zugzwang03** [comment]
> Please merge this I have done all required edits

Kindly link your PR with the respective issue. 
Also don't make any indentation changes, it causes unnecessary merge conflicts for other contributors later.

**Comment by Saksham-1612** [comment]
> > Please merge this I have done all required edits
> 
> Kindly link your PR with the respective issue. Also don't make any indentation changes, it causes unnecessary merge conflicts for other contributors later.

Done I have linked pr with issue #54 .
Now i can't do anything for indentation changes but will make sure no to do this from next time.

**Review by Vanshiii203 — CHANGES_REQUESTED** [review]
Please delete the Product Launching website folder

**Comment by Saksham-1612** [comment]
@Vanshiii203 I did the required changes please check it once again. I hope it would be approved

**Review by Vanshiii203 — CHANGES_REQUESTED** [review]
You have committed changes in the Product launching website. Please look into it

**Comment by Saksham-1612** [comment]
@Vanshiii203  I think I have messed up with other files. Now can I raise a new pr and just paste my project files in that without changing anythingg

**Pull request closed without merging**
