### PR TITLE
I just change background color .

### PR DESCRIPTION
**Pull request by rashi24-p**
I change the background color.

### CODE REVIEW

**Review by LiQuiD-404 — CHANGES_REQUESTED** [review]
@rashi24-p can you please share some screenshots of your project?

**Review by harshit-paneri — CHANGES_REQUESTED** [review]
Add screenshot in conversation and update readme pic also

**Comment by rashi24-p** [comment]
> @rashi24-p can you please share some screenshots of your project?
okay, I"ll share u.

**Comment by rashi24-p** [comment]
> @rashi24-p can you please share some screenshots of your project?


> @rashi24-p can you please share some screenshots of your project?

@LiQuiD-404 Screenshots of the project.

S2
S3

**Pull request closed without merging**
