### PR TITLE
added Filters

### PR DESCRIPTION
**Pull request by kuldeepjoshi27**
issue number = #370 

Screenshots:-

Screenshot 2023-01-21 125844
Screenshot 2023-01-21 125911
Screenshot 2023-01-21 125932

### CODE REVIEW

**Review by LiQuiD-404 — CHANGES_REQUESTED** [review]
Kindly remove the Brick Breaker files from this PR. Also link your PR with the issue it is resolving.

**Comment by kuldeepjoshi27** [comment]
> Kindly remove the Brick Breaker files from this PR. Also link your PR with the issue it is resolving.

i have linked the issue resolved and the folder of brick breaker is not deleting i have closed a previos PR because of same issue and now it is again the same problem that the folder brick breaker is not removing

**Comment by LiQuiD-404** [comment]
@kuldeepjoshi27 Delete the forked repo and clone it again. That should work.

**Comment by kuldeepjoshi27** [comment]
> @kuldeepjoshi27 Delete the forked repo and clone it again. That should work.

i done it before with the same project but it is not working

**Pull request closed without merging**
