### PR TITLE
[SSoC 2.0] Solar System Model Ready

### LINKED ISSUE #1363: [SSoC 2.0] Solar System Model front end project
## **Describe the project**
A clear and concise description of the project you are going to add to this repository.
- Creating using HTML, CSS and JS
- Shows rotation of different planets around sun
- Tell about the some information on click like own mass, distance from the sun, etc.
- This will be very helpful from the point of view of children to learn about planets, solar system, etc. using visualization.

## Issue Type:

- [x] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

### PR DESCRIPTION
**Pull request by Avdhesh-Varshney**
## 🛠️ Issue (Number) - 1363

Closes #1363 

# Description

Please include a summary of the change. Please also include relevant motivation and context. List any dependencies that are required for this change.
- Adding responsiveness even for the mobile devices
- Adding data of all the solar bodies
- On hovering will flash the data on screen 
- Moving planets continuously around the sun

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] The title of my pull request is a short description of the requested changes.

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
Solar_System_Model

### CODE REVIEW

**Comment by Avdhesh-Varshney** [comment]
@zugzwang03 @TusharKesarwani please review this pull request and requested to merge it for a successful contribution under SSoC 2.0 program

**Comment by zugzwang03** [comment]
resolve conflicts

**Comment by Avdhesh-Varshney** [comment]
@TusharKesarwani @zugzwang03 Sirs, please again review this pull request and requested to merge for a successful contribution under SSoC 2.0 program

**Comment by Avdhesh-Varshney** [comment]
@TusharKesarwani Sir, please also review this pr and merge it also

Sir, i also requested to review my other prs also 1319 and 1415

**Comment by zugzwang03** [comment]
conflicts exist still

**Comment by Avdhesh-Varshney** [comment]
@TusharKesarwani @zugzwang03 Sirs, please again review this pr.
Conflicts Resolved !

**Comment by zugzwang03** [comment]
conflicts exist still.

**Comment by Avdhesh-Varshney** [comment]
@TusharKesarwani @zugzwang03 sir, please again review this pr
conflicts have resolved

**Review by TusharKesarwani — APPROVED** [review]

**Comment by TusharKesarwani** [comment]
If you're making changes in the main files then
You should take care of the syntax
Because of your PR whole website went down
This type of thing is not acceptable

**Pull request merged**
