### PR TITLE
[NEW PROJECT] Packers and Movers Website

### LINKED ISSUE #1684: Packers and Movers Website
## **Describe the project**
It is a website for a Packers and Movers Company - MoveIt.

## Issue Type:
- New Project

Screenshot (41)
Screenshot (42)
Screenshot (43)
Screenshot (44)
] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

### PR DESCRIPTION
**Pull request by blindaks**
Closes #1684 

# Description

I have added the project in the Projects section.

## Type of change

# Checklist:

- [x] I have made this from my own
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] The title of my pull request is a short description of the requested changes.

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Comment by blindaks** [comment]
@TusharKesarwani @zugzwang03 Please review this PR.

**Review by zugzwang03 — APPROVED** [review]

**Comment by blindaks** [comment]
@TusharKesarwani Please merge this PR.

**Comment by blindaks** [comment]
@TusharKesarwani

**Comment by blindaks** [comment]
@TusharKesarwani Please merge this PR.

**Review by TusharKesarwani — APPROVED** [review]

**Pull request merged**
