### PR TITLE
Stone, paper & scissor game (issue  #52)

### PR DESCRIPTION
**Pull request by ashadmuneer**
I have made four files index.html(containing html code), style.css (containing style) , main.js and one folder of images

### CODE REVIEW

**Comment by Vanshiii203** [comment]
@ashadmuneer Add a pic of the project in the comment section

**Comment by ashadmuneer** [comment]
@Vanshiii203 
Untitled

**Comment by Vanshiii203** [comment]
@ashadmuneer Please link the issue which you have resolved !

**Review by Vanshiii203 — APPROVED** [review]
LGTM!

**Comment by ashadmuneer** [comment]
@Vanshiii203 
issue link [#52 ](url)

**Review by TusharKesarwani — APPROVED** [review]

**Pull request merged**
