### PR TITLE
To sovle the problem of performing one arithmetic function(#783)

### PR DESCRIPTION
**Pull request by 2020B1531074**
Screenshot (151)
to solve the problem of performing one arithmetic operation

## 🛠️ Issue (Number)
#783 
in the screenshot we can see it performs multiple operation together. 

Closes #

# Description

Please include a summary of the change. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ ] I have made this from my own
- [ ] I have taken help from some online resourses 
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] The title of my pull request is a short description of the requested changes.

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Comment by 2020B1531074** [comment]
#783

**Comment by 2020B1531074** [comment]
#783 
project deployment link:https://nimble-swan-4a0e59.netlify.app/
netlify deployment link:https://deploy-preview-901--frontendprojects.netlify.app/

**Comment by 2020B1531074** [comment]
In the calculator when we perform more than arithmetic operations like
8+9*3-6/2 then it does not work so I improve this code so that it can
perform multiple arithmetic operations and the user does not face problems.
I also shared the screenshot in which you can see many arithmetic
operations together can perform

**Comment by Abhishantpadam** [comment]
But your code still has flows like its still taking multiple operators i means taking more than 1 operator after inputing number let me share the screenshot again.
Screenshot 2023-06-03 at 2 56 37 AM

See the input in the screenshot

**Comment by 2020B1531074** [comment]
On Sat, Jun 3, 2023, 2:57 AM Abhishantpadam ***@***.***>
wrote:

> But your code still has flows like its still taking multiple operators i
> means taking more than 1 operator after inputing number let me share the
> screenshot again.
> [image: Screenshot 2023-06-03 at 2 56 37 AM]
> <https://user-images.githubusercontent.com/46023761/242994289-4ed63e20-32f1-46c3-8283-b74212309f76.png>
>
> See the input in the screenshot
>
Bro , in this input there is many operators but I resolve for more than two
operand but this input you take in this screenshot should be error. But I
solve for more than two operand . I check first it also does not work for
two operand previously.

**Comment by Abhishantpadam** [comment]
but the issue is not opened for multiple operand its opened for operators the error is that why it is taking multiple operators i have raised the issue for that not for operand and i have fixed that issue. And by fixing it it will automatically solve the multiple operand issue.

**Comment by 2020B1531074** [comment]
Let me show to the screenshot in which you have a taken a input .show me a
output of input according to your code as you send me a screenshot (u take
input) .it should also be error and I have a question how it label add on
particular one issue and how we score get in quine .Is it after the merging
of pr?

**Comment by Abhishantpadam** [comment]
Here try this 
https://replit.com/@Atticus7898/calculator#js/script.js
check the live preview of the corrected code.

**Review by harshit-paneri — APPROVED** [review]

**Pull request closed without merging**
