### PR TITLE
listed some projects on homepage from the projects directory and fixed links in homepage

### PR DESCRIPTION
**Pull request by HeySkidee**
## 🛠️ Issue (Number)

Closes #

# Description

Please include a summary of the change. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ ] I have made this from my own
- [ ] I have taken help from some online resources 
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] The title of my pull request is a short description of the requested changes.

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Comment by TusharKesarwani** [comment]
Great, If you can add all projects then Add each and every project and make a fresh PR

**Comment by TusharKesarwani** [comment]
And also create an issue for that first

**Comment by HeySkidee** [comment]
can you merge this request for now till I add other projects?
the website is pretty empty now and multiple people visit it everyday
i'll create a separate PR for other projects that i'll add

**Comment by TusharKesarwani** [comment]
> can you merge this request for now till I add other projects? the website is pretty empty now and multiple people visit it everyday i'll create a separate PR for other projects that i'll add
Sorry, If you can add all projects then Add each and every project and make a fresh PR
This PR will not be merged

**Pull request closed without merging**
