### PR TITLE
Dynamic js quiz

### LINKED ISSUE #388: Dynamic JS quiz
## **Describe the project**
This Project Teaches You About Radio Buttons And How To Use JavaScript To Add Content.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [ ] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

### PR DESCRIPTION
**Pull request by Laraibnehal**
## 🛠️ #388

Closes #388 

# Description

This Project Teaches You About Radio Buttons And How To Use JavaScript To Add Content.
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ x] I have made this from my own
- [x ] I have taken help from some online resourses 
- [ x] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [x ] My changes generate no new warnings
- [x ] The title of my pull request is a short description of the requested changes.

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Review by Vanshiii203 — CHANGES_REQUESTED** [review]
Add a Readme.md file for your project

**Comment by Laraibnehal** [comment]
ok

**Review by Vanshiii203 — CHANGES_REQUESTED** [review]
attach a screenshot of project in readme.md file

**Comment by Laraibnehal** [comment]
@Vanshiii203

**Review by Vanshiii203 — CHANGES_REQUESTED** [review]
Remove the files of survey form

**Comment by Laraibnehal** [comment]
Done @Vanshiii203

**Review by Vanshiii203 — APPROVED** [review]

**Review by TusharKesarwani — APPROVED** [review]

**Pull request merged**
