### PR TITLE
[SSoC 2.0] Maths Website for Practising

### LINKED ISSUE #1634: [SSoC 2.0] Math Puzzle website for children
## **Describe the project**
Title - Math Practice
Tech using - HTML, CSS and JS

- Options for addition, subtraction, multiplication, division, percentage, etc. calculations for practising.
- Questions will comes accordingly as selections.
- Creating a sound on each correct answer and wrong answer so to attract children more and more.
- Responsive for the small devices too.

## Issue Type:

- [x] New Project

## **Additional context**
- Very helpful for the children

### PR DESCRIPTION
**Pull request by Avdhesh-Varshney**
## 🛠️ Issue (Number) - 1634

Closes #1634 

# Description
1. Select the option you want to practice.
2. Calculate and write your ans in the box and click check answer.
3. Alert will be given if the ans is write or wrong .
4. Click ok to continue the quiz.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] The title of my pull request is a short description of the requested changes.

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
image

### CODE REVIEW

**Comment by Avdhesh-Varshney** [comment]
@harshit-paneri @TusharKesarwani @zugzwang03 sir, please review this pr

**Review by zugzwang03 — APPROVED** [review]

**Review by zugzwang03 — CHANGES_REQUESTED** [review]
image
not working as expected

**Comment by Avdhesh-Varshney** [comment]
@zugzwang03 @TusharKesarwani @harshit-paneri sir, please again review this pull request

**Review by zugzwang03 — APPROVED** [review]

**Comment by TusharKesarwani** [comment]
Game projects are not accepted

**Pull request closed without merging**
