### PR TITLE
Added Magic-Ball folder

### PR DESCRIPTION
**Pull request by manni2000**
Hi there, I'm added small project magic-ball. Please reviewed that!
Thank you

### CODE REVIEW

**Review by harshit-paneri — CHANGES_REQUESTED** [review]
Add readme file and screen shot also

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
Link the issue first ! Also please add a Readme explaining your project

**Review by Vanshiii203 — CHANGES_REQUESTED** [review]
Link the issue with the PR and write the tech stack used and attach screenshot of project in the readme.md file

**Comment by manni2000** [comment]
I'm already giving PR and tech stack used - HTML, CSS, Javascript & Readme & Photo are already attached. Please look at it carefully.
Thank you

**Review by TusharKesarwani — APPROVED** [review]

**Review by siddhi-244 — APPROVED** [review]

**Review by harshit-paneri — APPROVED** [review]

**Review by Vanshiii203 — CHANGES_REQUESTED** [review]
You have created a normal file, create a readme.md (markdown file) file and write the project description, tech stack used and screenshot of project in that file

**Comment by manni2000** [comment]
I'm done with all requirements.
Thank you

**Review by Vanshiii203 — APPROVED** [review]

**Review by TusharKesarwani — APPROVED** [review]

**Pull request merged**
