### PR TITLE
PR for Meditation-App with respect to issue#257

### PR DESCRIPTION
**Pull request by monishkajha17**
With respect to issue #257

### CODE REVIEW

**Review by Vanshiii203 — CHANGES_REQUESTED** [review]
image
the images are not visible. 
Link the PR with issue number

**Comment by monishkajha17** [comment]
@Vanshiii203 Kindly Check Now

**Review by Vanshiii203 — CHANGES_REQUESTED** [review]
Have you added any sound because it is not working and the timer button isnot functioning the way it is supposed to be.
image
Also,the alignment of the images is not correct 
Kindly fix these issues

**Comment by monishkajha17** [comment]
ok di

**Pull request closed without merging**
