### PR TITLE
Added new files

### LINKED ISSUE #1355: Adding My new project to the repo.
## **Describe the project**
Chromatic Chaos: A dynamic browser-based art experience fusing Paper.js and splatter paint. Unleash your creativity, defy boundaries, and embark on an extraordinary journey of abstract expression.
## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x ] New Project

### PR DESCRIPTION
**Pull request by Pyth0nHere**
## 🛠️ Issue (Number)

Closes #1355 

# Description

I Added my own Project to the repo!

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x ] I have made this from my own
- [ x] I have taken help from some online resourses 
- [ ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ x] My changes generate no new warnings
- [ ] The title of my pull request is a short description of the requested changes.

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Review by harshit-paneri — APPROVED** [review]

**Comment by Pyth0nHere** [comment]
When this project is getting merged? @harshit-paneri @TusharKesarwani

**Comment by harshit-paneri** [comment]
> When this project is getting merged? @harshit-paneri @TusharKesarwani

It will merge by project admin @TusharKesarwani

**Review by Arun9739 — APPROVED** [review]

**Review by Pyth0nHere — COMMENTED** [review]
Fixed the bug, now it's ready to deploy and merged.

**Review by TusharKesarwani — CHANGES_REQUESTED** [review]
Not working

**Pull request closed without merging**
