### PR TITLE
Merge Pull Request #312 from radzhiv25

### LINKED ISSUE #312: QR scanning app using HTML,CSS and JS
A basic QR scanner app where it can distinguish QR and an image then scan it using HTML, CSS and vanilla JS

### PR DESCRIPTION
**Pull request by radzhiv25**
## 🛠️ Issue (Number) 
Closes #312 

# Description
Made a QR Reader using HTML,CSS and vanilla Js which can distinguish between images and QR 

## Type of change

- [X] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] The title of my pull request is a short description of the requested changes.

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
image

### CODE REVIEW

**Review by radzhiv25 — COMMENTED** [review]
Please check the PR

**Review by Vanshiii203 — APPROVED** [review]

**Review by Rishikavishnoi — APPROVED** [review]

**Comment by TusharKesarwani** [comment]
Screenshot
Not working for many QR codes

**Comment by radzhiv25** [comment]
> Screenshot
> 
> Not working for many QR codes

Ok will figure it out

**Pull request closed without merging**
