### PR TITLE
ADD : Resume Creator

### LINKED ISSUE #832: Resume Creator using Basic JavaScript
## **Describe the project**
This project uses Basic HTML, CSS, JavaScript to create a basic Resume Creator, where you can create your resume and most important download the created Resume.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [X] New Project

## **Additional context**
Created using HTML, CSS, JS only

## **Screenshots**
| Edit View | Download View |
|----- | ----- |
|Screenshot_20221224_152627 |Screenshot_20221224_150727 |

### PR DESCRIPTION
**Pull request by dev-AshishRanjan**
## 🛠️ Issue (Number)

Closes #832 

# Description

Please include a summary of the change. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [X] I have made this from my own
- [X] I have taken help from some online resourses 
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] The title of my pull request is a short description of the requested changes.

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
Screenshot_20221224_150710

### CODE REVIEW

**Comment by harshit-paneri** [comment]
> ### ✅ Deploy Preview for _frontendprojects_ ready!
> Name	Link
> 🔨 Latest commit	[3bd3d2e](https://github.com/TusharKesarwani/Front-End-Projects/commit/3bd3d2eb171a4b3abe0368752c4ba2b226861d07)
> 🔍 Latest deploy log	https://app.netlify.com/sites/frontendprojects/deploys/64838b02258a3f0007bb97f6
> 😎 Deploy Preview	https://deploy-preview-1090--frontendprojects.netlify.app
> 📱 Preview on mobile	
> Toggle QR Code...
> _To edit notification comments on pull requests, go to your [Netlify site settings](https://app.netlify.com/sites/frontendprojects/settings/deploys#deploy-notifications)._

deploy preview link ??
@dev-AshishRanjan

**Comment by dev-AshishRanjan** [comment]
> > ### ✅ Deploy Preview for _frontendprojects_ ready!
> > Name	Link
> > 🔨 Latest commit	[3bd3d2e](https://github.com/TusharKesarwani/Front-End-Projects/commit/3bd3d2eb171a4b3abe0368752c4ba2b226861d07)
> > 🔍 Latest deploy log	https://app.netlify.com/sites/frontendprojects/deploys/64838b02258a3f0007bb97f6
> > 😎 Deploy Preview	https://deploy-preview-1090--frontendprojects.netlify.app
> > 📱 Preview on mobile
> > Toggle QR Code...
> > _To edit notification comments on pull requests, go to your [Netlify site settings](https://app.netlify.com/sites/frontendprojects/settings/deploys#deploy-notifications)._
> 
> deploy preview link ?? @dev-AshishRanjan

deploy preview link - https://deploy-preview-1090--frontendprojects.netlify.app/

**Comment by harshit-paneri** [comment]
> > > ### ✅ Deploy Preview for _frontendprojects_ ready!
> > > Name	Link
> > > 🔨 Latest commit	[3bd3d2e](https://github.com/TusharKesarwani/Front-End-Projects/commit/3bd3d2eb171a4b3abe0368752c4ba2b226861d07)
> > > 🔍 Latest deploy log	https://app.netlify.com/sites/frontendprojects/deploys/64838b02258a3f0007bb97f6
> > > 😎 Deploy Preview	https://deploy-preview-1090--frontendprojects.netlify.app
> > > 📱 Preview on mobile
> > > Toggle QR Code...
> > > _To edit notification comments on pull requests, go to your [Netlify site settings](https://app.netlify.com/sites/frontendprojects/settings/deploys#deploy-notifications)._
> > 
> > 
> > deploy preview link ?? @dev-AshishRanjan
> 
> deploy preview link - https://deploy-preview-1090--frontendprojects.netlify.app/

your project preview link ??

**Comment by dev-AshishRanjan** [comment]
sorry for the confusion

My project preview link - https://deploy-preview-1090--frontendprojects.netlify.app/projects/resume%20creator/

**Review by harshit-paneri — APPROVED** [review]
Great

**Review by TusharKesarwani — APPROVED** [review]

**Comment by TusharKesarwani** [comment]
Resolve the conflicts

**Comment by dev-AshishRanjan** [comment]
> Resolve the conflicts

It's done

**Pull request merged**
