### PR TITLE
[SSoC 2.0] Number to Words Convertor Project Completed

### LINKED ISSUE #1296: [SSoC 2.0] Number to words convertor front end project
## **Describe the project**
- Enter the number in the input box
- Using Javascript, convert the entered number into words
- Number to words conversion is done instantly on entering the number

## Issue Type:

- [x] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

### PR DESCRIPTION
**Pull request by Avdhesh-Varshney**
## 🛠️ Issue (Number)

Closes #1296 

# Description

Please include a summary of the change. Please also include relevant motivation and context. List any dependencies that are required for this change.
- Enter the number in the input box
- Using Javascript, convert the entered number into words
- Number to words conversion is done instantly on entering the number

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] The title of my pull request is a short description of the requested changes.

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
Number_To_Words_Convertor

### CODE REVIEW

**Comment by Avdhesh-Varshney** [comment]
@TusharKesarwani please review this pull request and requested to merge it into the main branch of this repository for a valuable contribution under SSoC 2.0 program
Ans Thanks for assigning me this project.

**Review by zugzwang03 — APPROVED** [review]

**Comment by Avdhesh-Varshney** [comment]
@TusharKesarwani Sir, this pr is ready to merge. 

I requested to merge this pr for a contribution under SSoC 2.0 program

**Review by TusharKesarwani — APPROVED** [review]

**Comment by TusharKesarwani** [comment]
Resolve merge conflicts

**Comment by Avdhesh-Varshney** [comment]
@TusharKesarwani Sir, i have resolved the conflicts, please again review this pr and merge it into the main branch for a successful contribution under SSoC 2.0 program

**Comment by Avdhesh-Varshney** [comment]
@TusharKesarwani Sir, please also review this pr and merge it also

**Comment by zugzwang03** [comment]
resolve conflicts first

**Comment by Avdhesh-Varshney** [comment]
@TusharKesarwani @zugzwang03 Sirs, please again review this pull request and merge it for a successful contribution under SSoC 2.0 program

**Comment by Avdhesh-Varshney** [comment]
@TusharKesarwani @zugzwang03 Sirs, please merge this pr then i will resolve the conflicts of the other pr

**Review by zugzwang03 — APPROVED** [review]

**Comment by Avdhesh-Varshney** [comment]
@TusharKesarwani Sir, i requested to merge this pull request as now this pr does not have any conflicts at this time.

**Comment by TusharKesarwani** [comment]
Project is already present in the repo

**Pull request closed without merging**
