### PR TITLE
QR Code Generator

### PR DESCRIPTION
**Pull request by suvamita**
#134
Description: Generation QR code from entered URL, text using HTML, CSS, JS.
Screenshot:
ScreenShot_QR Code Generator

### CODE REVIEW

**Review by Vanshiii203 — CHANGES_REQUESTED** [review]
Please add a README.md file in the project with the explanation of your project, tech stack used, and screenshot of the project
Also, link the issue with the PR

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
Please link the issue properly  (using a #)

**Comment by Vanshiii203** [comment]
@suvamita  Please attach screenshots of your project in the Readme.md file. Also, you have added the project files directly; create a folder (named as your project name), add the project files to that folder, and then push the changes.

**Comment by Vanshiii203** [comment]
@suvamita delete the files which are outside the folder

**Review by Vanshiii203 — APPROVED** [review]
LGTM🙌

**Review by siddhi-244 — APPROVED** [review]
LGTM

**Review by TusharKesarwani — APPROVED** [review]

**Pull request merged**
