### PR TITLE
OTP Verification #279

### PR DESCRIPTION
**Pull request by Sreehitha2003**

### CODE REVIEW

**Review by harshit-paneri — CHANGES_REQUESTED** [review]
Hey @Sreehitha2003 , Please add Reame file also and images too.

**Comment by Sreehitha2003** [comment]
> Hey @Sreehitha2003 , Please add Reame file also and images too.

Yes i did

**Review by Vanshiii203 — CHANGES_REQUESTED** [review]
Add the screenshot of project in Readme.md file

**Comment by Sreehitha2003** [comment]
> Add the screenshot of project in Readme.md file

I did

**Review by harshit-paneri — APPROVED** [review]

**Review by TusharKesarwani — APPROVED** [review]

**Pull request merged**
