### PR TITLE
Clone of SB UI KIT PRO

### LINKED ISSUE #554: SB UI KIT Clone Website
## **Describe the project**
It is a clone of SB UI KIT Website . with a color customizer embeded.

## Issue Type:

- [x] New Project

### PR DESCRIPTION
**Pull request by khushimarothi**
## 🛠️ Issue (Number)

Closes #554 

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

- [x] My changes generate no new warnings
- [x] The title of my pull request is a short description of the requested changes.

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
https://khushimarothi.github.io/Project8/SB%20UI%20KIT%20PRO/Home.html

### CODE REVIEW

**Review by himanshu1221 — CHANGES_REQUESTED** [review]
You can add a discription of your website below checklist

**Review by zugzwang03 — CHANGES_REQUESTED** [review]
Add a README.md file

**Review by zugzwang03 — COMMENTED** [review]
You are not assigned this issue @khushimarothi .
Don't raise PRs before getting assigned.

**Review by zugzwang03 — APPROVED** [review]

**Review by Vanshiii203 — CHANGES_REQUESTED** [review]
Add a readme.md file for your project

**Pull request closed without merging**
