### PR TITLE
Finance Tracker

### LINKED ISSUE #887: Finance Tracker
## **Describe the project**
Create a web-based personal finance tracker using JavaScript, HTML, and CSS. The application should allow users to add, edit, and delete income and expense transactions and display the current balance. 
## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [* ] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

image
image

### PR DESCRIPTION
**Pull request by AMRIT456**
## 🛠️ Issue (Number)

Closes #887 

# Description

I have fixed the bug and the project is running smoothely.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [ ] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] The title of my pull request is a short description of the requested changes.

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
image
image

### CODE REVIEW

**Review by zugzwang03 — CHANGES_REQUESTED** [review]
add README

**Review by zugzwang03 — CHANGES_REQUESTED** [review]
update branch

**Comment by AMRIT456** [comment]
@zugzwang03  Added README FILE and updated the branch

**Comment by zugzwang03** [comment]
image
it is not updated

**Comment by AMRIT456** [comment]
@zugzwang03  please check it again from my computer it is saying everything up to date.
image
please help me if i have done something wrong.

**Comment by AMRIT456** [comment]
please reveiw this

**Comment by zugzwang03** [comment]
update from your forked repo

**Pull request closed without merging**
