### PR TITLE
Fixed issue with moving to the next question without selecting an option

### PR DESCRIPTION
**Pull request by Divyanshu9822**
## 🛠️ Issue (#906)

# Description

This pull request addresses the issue raised (#IssueNumber) regarding the inability to move to the next question without selecting an option in the "Dynamic Quiz Js" project.

## Changes Made:

- Modified the code to allow the user to proceed to the next question even if no option is selected.
- Implemented a counter for unmarked questions and utilised to show final result.

## Testing Done:

- Tested the updated functionality by navigating through the quiz and verifying that the user can move to the next question without selecting an option. 
- Tested the Start Over functionality many times to verify no bugs left.

# Screenshot:

The screenshot attached below shows 0 questions answered i.e. this resolves the passing and moving to next question without selecting an option.

image

### CODE REVIEW

**Comment by Divyanshu9822** [comment]
Hey @harshit-paneri , Please review the changes which solves the issue #906 and merge this pull request if it meets the requirements.

Thanks

**Review by harshit-paneri — CHANGES_REQUESTED** [review]
Where is search functionality in this

**Comment by Divyanshu9822** [comment]
@harshit-paneri sir this was not for the search functionality. this resolves issue under #906 which was that this does not allow user to move forward without marking the question

**Review by harshit-paneri — APPROVED** [review]
Mandatory Answer the quiz

**Comment by Divyanshu9822** [comment]
@harshit-paneri This is quiz project which doesn't let user move to next question on clicking Next as it alters user by showing "Pls select an option" but under this Pr this is resolved as now user can freely leave any question and can see the result with no. of correct questions and no. of unmarked questions i.e. left questions.

**Comment by harshit-paneri** [comment]
> @harshit-paneri This is quiz project which doesn't let user move to next question on clicking Next as it alters user by showing "Pls select an option" but under this Pr this is resolved as now user can freely leave any question and can see the result with no. of correct questions and no. of unmarked questions i.e. left questions.

Yup✨✨

**Comment by Divyanshu9822** [comment]
Sir @harshit-paneri changes doesn't reflect in repo. how to merge these approved requests ? As I've resolved two issues and previous one was also approved but was not merged, merging my both PR at once will cause merge conflict i guess.

**Comment by harshit-paneri** [comment]
> Sir @harshit-paneri changes doesn't reflect in repo. how to merge these approved requests ? As I've resolved two issues and previous one was also approved but was not merged, merging my both PR at once will cause merge conflict i guess.

Merge will be done by project admin.

**Pull request merged**
