### PR TITLE
Hotstar Clone[SSOC'23]

### LINKED ISSUE #1714: Hotstar Clone[SSOC'23]
## **Describe the project**
Hello Sir ,👋
I am Arpan Chowdhury, a aspiring Web developer.🤖 I want to add my **HOTSTAR Clone**📺 project under SSoC'23.😁We all use this most used steaming Platform. I have made it with the use of HTML,CSS & JS.
It is basically the landing Page of HOTSTAR application where you can see

- Subscribe, login , search bar🔎
- Some cards of the popular series
- Some small animations🦊
- Some cards of popular shows
## Issue Type:

- [] Bug Report
- [] Feature Request
- [] Documentation
- [X] New Project

## **Additional context**

# Video
https://github.com/apu52/HotstarClone/assets/114172928/0e0cf7e7-5509-4170-9a3a-adc53583929a
## **Screenshots**
hotstar
Please assign me this issue under SSOC 2.0 🙏 
- If applicable, add screenshots to help explain your problem.

### PR DESCRIPTION
**Pull request by apu52**
## 🛠️ Issue (Number)

Closes #1714 

# Description

Hello Sir👨‍💻 ,I am Arpan Chowdhury, a aspiring Web developer.🤖 Here is the project of the front-end Web Developement. We all use the most famous streaming platform HOTSTAR. So, here is the frontend clone of the landing page👆🏻 .

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] The title of my pull request is a short description of the requested changes.

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

hotstar

### CODE REVIEW

**Comment by apu52** [comment]
@TusharKesarwani I have added my PR . Please take areview & merge my PR under SSoC 2.0

**Review by harshit-paneri — CHANGES_REQUESTED** [review]
Images are not showing.

**Comment by apu52** [comment]
@TusharKesarwani @harshit-paneri I have added the image & Video folder to the PR. Please take a look & please take  a review & merge it under SSOC 2.0

**Review by TusharKesarwani — APPROVED** [review]

**Review by TusharKesarwani — CHANGES_REQUESTED** [review]
Change the path to dynamic path for images

**Comment by apu52** [comment]
@TusharKesarwani I have changed the paths of the images. Please take a review of my PR & merge it under SSOC'23

**Review by TusharKesarwani — APPROVED** [review]

**Pull request merged**
