### PR TITLE
Feat: Realtime Currency Converter Project using API.

### LINKED ISSUE #863: New Project: Realtime Currency Converter using API.
## Realtime Currency Converter

This is a currency converter web application that fetches real-time data for currency conversion rates using HTML, CSS, and JavaScript. The application allows users to convert currencies by selecting the source currency and the target currency, and it provides an interface to easily switch between the two selected values.

## Issue Type:

- [x] New Project

## **Additional context**

- Real-time currency conversion rates using an API
- Simple and intuitive user interface
- Select source currency and target currency
- Button to switch the selected currencies
- Display of the converted currency value

## **Screenshots**

Image 1

### PR DESCRIPTION
**Pull request by Alkaison**
## 🛠️ New Project: Realtime Currency Converter Project using API.

Closes #863 

# Description

This is a currency converter web application that fetches real-time data for currency conversion rates using HTML, CSS, and JavaScript. The application allows users to convert currencies by selecting the source currency and the target currency, and it provides an interface to easily switch between the two selected values.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue) #863 
- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made this from my own
- [x] The title of my pull request is a short description of the requested changes.

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

- Deployement: https://alkaison.github.io/Currency-Converter/

- Image

### CODE REVIEW

**Comment by Alkaison** [comment]
## Completed Project: Realtime Currency Converter Project using API.

- PR Deployment link: https://deploy-preview-864--frontendprojects.netlify.app/

- Project Deployment link: https://deploy-preview-864--frontendprojects.netlify.app/projects/realtime%20currency%20converter/

### Please review the PR and merge it, Thanks in advance.

## Screenshot

image

**Comment by Alkaison** [comment]
Hi @TusharKesarwani, waiting for your response.

**Comment by Arun9739** [comment]
@Alkaison Add a README in your project folder, and describe your poject there.

**Comment by Alkaison** [comment]
Hi @Arun9739, I recently pushed commits on the same branch as this PR but its not reflecting here. Is there any problem? 

Committed at 07-June-2023 11:05 PM, Indian Time.

Please check: https://github.com/Alkaison/Front-End-Projects/tree/RealtimeCurrencyConverterProject

### Screenshot

image

**Comment by Arun9739** [comment]
@Alkaison It is reflected. Plzz resolve the branch conflicts.

**Comment by Alkaison** [comment]
Hi @Arun9739, resolved the conflict, now it's ready to get merged! 🎉

**Review by Arun9739 — APPROVED** [review]

**Comment by Alkaison** [comment]
Hi @Arun9739, Thanks for approving this PR. Can you please add the `SSoC` label to this PR. Hope it gets merged soon!

**Review by TusharKesarwani — APPROVED** [review]

**Pull request merged**
