### PR TITLE
Anime Website

### PR DESCRIPTION
**Pull request by Harshit-Raj-14**
I have made a complete layout of a static anime website.

Issue No.: #615 

Website screenshot:
Screenshot 2023-03-11 at 10-22-29 Anime Website

### CODE REVIEW

**Comment by siddhi-244** [comment]
@Harshit-Raj-14 this is assigned to someone else !

**Comment by Harshit-Raj-14** [comment]
@siddhi-244 Yes, I saw, but the last update on that issue was a month ago. So, possibly it was dropped by the one who raised the issue. Since the SWOC is ending and I had made the project. I thought of contributing. Can it still be accepted.

**Comment by Harshit-Raj-14** [comment]
@siddhi-244 @Vanshiii203  Yes, I saw, that it was assigned to someone else, but the last update on that issue was a month ago. So, possibly it was dropped by the one who raised the issue. Since the SWOC is ending and I had made the project. I thought of contributing. Can it still be accepted. 

Thank you.

**Comment by Vanshiii203** [comment]
> @siddhi-244 @Vanshiii203 Yes, I saw, that it was assigned to someone else, but the last update on that issue was a month ago. So, possibly it was dropped by the one who raised the issue. Since the SWOC is ending and I had made the project. I thought of contributing. Can it still be accepted.
> 
> Thank you.

Comment under the issue and get it assigned to yourself and then you can raise a PR

**Pull request closed without merging**
