### PR TITLE
Weather 

### LINKED ISSUE #1155: Dropdown menu of Weather site
**Describe the bug**
There is a line after the second place name which is not required in the dropdown menu of places.

**Screenshots**

Screenshot (44)

I want to remove that line and make it look good,
Please assign me this issue @TusharKesarwani

### PR DESCRIPTION
**Pull request by suma30**
## 🛠️ Issue (Number)

Closes #1155 

# Description

Added a divider in between the list items of dropdown menu,
Added a name entity for dropdown symbol for better understanding,
Created and linked About page and linked it to the main page,
Created and linked Usage Guide page and linked it to the main page
## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [ ] I have taken help from some online resourses 
- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by suma30** [comment]
@TusharKesarwani @zugzwang03 Please check my PR request for weather site

**Comment by suma30** [comment]
@zugzwang03 after updating the branch should I create a new PR, what should I do, please give me some idea

**Comment by suma30** [comment]
@zugzwang03 please check the PR now, did it get updated

**Review by zugzwang03 — APPROVED** [review]

**Comment by suma30** [comment]
@TusharKesarwani @zugzwang03 Could you please merge this PR raised for weather site

**Review by TusharKesarwani — APPROVED** [review]

**Pull request merged**
