### PR TITLE
Feat/issue 1886/revamp note app

### LINKED ISSUE #1886: UX/UI Improvement for Note app
**Is your feature request related to a problem? Please describe.**
There's alot of improvement that need to be done to note app. The app isn't responsive at all, and still lacks some important features

**Describe the solution you'd like**
I would love to improve the app to a much more better note taking application which would serve as a real product users would be willing to use.

**Additional context**
Screenshot 2023-07-29 at 14 57 30

### PR DESCRIPTION
**Pull request by Benrobo**
## 🛠️ Issue (Number)

Closes #1886

# Description

Revamp the app UI and functionalities.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ ] I have made this from my own
- [ ] I have taken help from some online resourses 
- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] The title of my pull request is a short description of the requested changes.

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

[Live Url](https://deploy-preview-1915--frontendprojects.netlify.app/projects/notes_app/)

Screenshot 2023-08-03 at 6 32 14 AM

### CODE REVIEW

**Review by TusharKesarwani — CHANGES_REQUESTED** [review]
**Not working**
New button is not working

**Comment by Benrobo** [comment]
> **Not working** New button is not working

Ok @TusharKesarwani would fix that today

**Comment by Benrobo** [comment]
@TusharKesarwani  bug has been fixed. Here is the deployed url [Live Url](https://deploy-preview-1915--frontendprojects.netlify.app/projects/notes_app/)

**Comment by Benrobo** [comment]
@TusharKesarwani please kindly check my PR.

**Review by TusharKesarwani — APPROVED** [review]

**Pull request merged**
