### PR TITLE
Password Checker

### LINKED ISSUE #1692: Password Checker
## **Describe the project**
Password Checker checks , How secure is your password?

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [✅] New Project

## **Additional context**
Password Checker checks whether password is strong enough or not

## **Screenshots**
image

### PR DESCRIPTION
**Pull request by Devchawla2608**
password checker

## 🛠️ Issue (1692)
Closes #1692

# Description

Password Checker checks that How Secure is Your Password

## Type of change

- [✅] New feature (non-breaking change which adds functionality)

# Checklist:

- [✅] I have made this from my own
- [✅] I have taken help from some online resourses 
- [✅] My code follows the style guidelines of this project
- [✅] I have performed a self-review of my own code
- [✅] My changes generate no new warnings
- [✅] The title of my pull request is a short description of the requested changes.

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
image
https://passwordstrengthcheckerssoc3.netlify.app/

### CODE REVIEW

**Comment by Devchawla2608** [comment]
@zugzwang03 please review my pr

**Comment by harshit-paneri** [comment]
issue link

**Review by zugzwang03 — CHANGES_REQUESTED** [review]
add issue link

**Comment by Devchawla2608** [comment]
@zugzwang03 @harshit-paneri  Issue link added

**Comment by zugzwang03** [comment]
update branch first

**Review by zugzwang03 — APPROVED** [review]

**Review by TusharKesarwani — APPROVED** [review]

**Pull request merged**
