### PR TITLE
Messi Mania

### LINKED ISSUE #1288: Want to add my open source project MESSI MANIA
## **Describe the project**
A simple fan made web-page of LIONEL MESSI
Made by HTML CSS and JavaScript

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

### PR DESCRIPTION
**Pull request by Soumyajit2825**
## 🛠️ Issue (Number)

Closes #1288 

# Description

It's a open source project using the basics HTML,CSS and JavaScript

# Checklist:

- [ ] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Review by TusharKesarwani — APPROVED** [review]

**Comment by TusharKesarwani** [comment]
Resolve merge conflicts

**Comment by Soumyajit2825** [comment]
@TusharKesarwani Done

**Review by zugzwang03 — APPROVED** [review]

**Comment by Soumyajit2825** [comment]
@TusharKesarwani @zugzwang03 Have you checked???
When do you merge it??

**Review by zugzwang03 — APPROVED** [review]

**Comment by Soumyajit2825** [comment]
@zugzwang03 When will you merge it?

**Comment by zugzwang03** [comment]
@TusharKesarwani will merge it, not me.

**Comment by Soumyajit2825** [comment]
@TusharKesarwani WHEN will you merge it??
It's been more than a week

**Comment by Soumyajit2825** [comment]
@TusharKesarwani hello
any update???

**Comment by Soumyajit2825** [comment]
@TusharKesarwani Hello!!

**Review by TusharKesarwani — APPROVED** [review]

**Pull request merged**
