### PR TITLE
Spotify Clone

### PR DESCRIPTION
**Pull request by himanshu1221**
## 🛠️ Issue (Number)
#430 
Closes #

# Description

Here i made a Spotify clone which is made up of using pure HTML CSS JAVASCRIPT this project was quite intresting and amazing as well as where HTML and CSS part was pretty easy the real struggle was with JavaScript and twitter tech,stackoveflow,stack exchage and youtube also helped me alot regarding this project it was quite amazing journey making this project !

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] The title of my pull request is a short description of the requested changes.

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
Screenshot from 2023-01-27 11-29-50
Screenshot from 2023-01-27 11-29-30
Screenshot from 2023-01-27 11-29-20

### CODE REVIEW

**Review by zugzwang03 — APPROVED** [review]

**Review by Rishikavishnoi — CHANGES_REQUESTED** [review]
@himanshu1221 Kindly add a README.md file to describe your project ...!

**Comment by himanshu1221** [comment]
> @himanshu1221 Kindly add a README.md file to describe your project ...!

added readme.md file please have a look

**Review by abhilipsasahoo03 — APPROVED** [review]
Looks good to me 👍

**Comment by himanshu1221** [comment]
> @himanshu1221 Kindly add a README.md file to describe your project ...!

Added Readme.md maam please have a look

**Review by TusharKesarwani — APPROVED** [review]

**Pull request merged**
