### PR TITLE
Added Online E-commerce Home Page

### LINKED ISSUE #476: Online Mart Home Page
## **Describe the project**
Developed a new online ecommerce basic website using HTML,CSS,Js.
It has a good features in it with good UX. 

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [X] New Project

## **Screenshots**
image
image

### PR DESCRIPTION
**Pull request by officialarmannqureshi**
## 🛠️ Issue (Number)

Closes #476 

# Description

I have added my own project into your project folder .It has been developed using HTML,CSS and Javascript.
Kindly check it out.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [X] I have made this from my own
- [X] I have taken help from some online resourses 
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] The title of my pull request is a short description of the requested changes.

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
image
image
image

### CODE REVIEW

**Comment by officialarmannqureshi** [comment]
Hi Sir I have made PR to your project.Kindly review it

**Review by harshit-paneri — CHANGES_REQUESTED** [review]
Add README.md file also

**Comment by officialarmannqureshi** [comment]
> Add README.md file also

done sir

**Review by harshit-paneri — CHANGES_REQUESTED** [review]
image

This is the view of you website, please correct there CSS

**Pull request closed without merging**
