### PR TITLE
Added Zomato Landing Page

### LINKED ISSUE #317: Zomato Landing Page Using HTML and CSS
Will create Zomato Landing Page Using only HTML and CSS

### PR DESCRIPTION
**Pull request by unikdahal**
Closes #317

### CODE REVIEW

**Comment by unikdahal** [comment]
Issue https://github.com/TusharKesarwani/Front-End-Projects/issues/317

**Review by LiQuiD-404 — CHANGES_REQUESTED** [review]
@unikdahal Kindly link your PR with your issue.

**Review by Vanshiii203 — APPROVED** [review]
LGTM

**Comment by unikdahal** [comment]
> @unikdahal Kindly link your PR with your issue.

@LiQuiD-404 Please check, I just linked the issue to this PR :)

**Review by TusharKesarwani — APPROVED** [review]

**Pull request merged**
