### PR TITLE
Calculator using HTML ,CSS and JS

### PR DESCRIPTION
**Pull request by Srishti-j18**
I have made four files index.html(containing html code), style.css (containing style) ,utils.css(containing utility classes) and main.js
Here is the deployment link for my calculator: 
https://srishti-j18.github.io/Srishti-jCaculator/

### CODE REVIEW

**Review by Vanshiii203 — APPROVED** [review]
LGTM

**Comment by Vanshiii203** [comment]
@Srishti-j18 Please link the issue which you have resolved !

**Comment by Srishti-j18** [comment]
> @Srishti-j18 Please link the issue which you have resolved !

issue no 60

**Comment by TusharKesarwani** [comment]
Calculator project is already present in the repo

**Comment by Srishti-j18** [comment]
> Calculator project is already present in the repo

Ok sir I will work on other issue.

**Pull request closed without merging**
