### PR TITLE
Added Flipkart Clone Project

### LINKED ISSUE #477: Flipkart Clone
## **Describe the project**
Hey, @TusharKesarwani I want to add the Flipkart clone project. Please assign me this issue. Thank you!

## Issue Type:

- [x] New Project

## **Additional context**
Flipkart clone made using HTML and CSS 

## **Screenshots**

Screenshot (569)

### PR DESCRIPTION
**Pull request by sumitkr2000**
## 🛠️ Issue (Number)

Closes #477 

# Description

Hey, @TusharKesarwani I have added the Flipkart clone project to your repo. Please review and merge my pr. Thank you!

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] The title of my pull request is a short description of the requested changes.

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
Screenshot (569)

### CODE REVIEW

**Review by Vanshiii203 — CHANGES_REQUESTED** [review]
make it responsive and add a readme.md file for your project

**Comment by sumitkr2000** [comment]
@ Vanshiii203 Could you check if it is responsive now? It took me 2 weeks to make it responsive. Uff... please merge it now and give me points. 🤒🤕

**Review by Vanshiii203 — CHANGES_REQUESTED** [review]
Add a readme for your project

**Comment by sumitkr2000** [comment]
@Vanshiii203 Done didi :)

**Review by Vanshiii203 — APPROVED** [review]

**Comment by sumitkr2000** [comment]
@TusharKesarwani Please merge my pr now. Thank you!

**Pull request merged**
