### PR TITLE
[SSoC 2.0] Random Meal Generator Project Completed

### LINKED ISSUE #1729: [SSoC 2.0] Random Meal Generator
## **Describe the project**
Title - Random Meal Generator
Tech using - HTML, CSS and JS

## Issue Type:

- [x] New Project

## **Additional context**
- Enter your weight.
- Press the button to generate meal.
- Project will generate random meal according to your weight.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

### PR DESCRIPTION
**Pull request by Avdhesh-Varshney**
## 🛠️ Issue (Number) - 1729

Closes #1729 

# Description
- This project can generate random meal

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] The title of my pull request is a short description of the requested changes.

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
https://github.com/TusharKesarwani/Front-End-Projects/assets/114330097/c4b9fbb1-81a4-422b-a33e-a97422a8477a

### CODE REVIEW

**Comment by Avdhesh-Varshney** [comment]
@harshit-paneri @TusharKesarwani @zugzwang03 sir, please review this pr

**Review by harshit-paneri — COMMENTED** [review]
Deploy link ??

**Comment by Avdhesh-Varshney** [comment]
https://github.com/TusharKesarwani/Front-End-Projects/assets/114330097/35ef6162-2214-4e8f-954e-bea68121bc35

<br>

[Deploy link](https://deploy-preview-1773--frontendprojects.netlify.app/projects/random-meal-generator/)

@harshit-paneri @TusharKesarwani @zugzwang03 sir, please again review this pull request

**Review by TusharKesarwani — APPROVED** [review]

**Comment by TusharKesarwani** [comment]
Resolve conflicts

**Comment by Avdhesh-Varshney** [comment]
@TusharKesarwani sir, conflicts resolved

**Comment by Avdhesh-Varshney** [comment]
@TusharKesarwani sir, please merge this pr

**Review by TusharKesarwani — APPROVED** [review]

**Pull request merged**
