### PR TITLE
University Management System 

### LINKED ISSUE #297: university management system website

### PR DESCRIPTION
**Pull request by sarasiddiquie**
Closes #297 

University Management system :

I have made a website which enables universities or schools to manage their academic activities. It is website with simple UI to ease the access of management.
There are certain features in the website as: 

1. Attendance
2. Notice
3. Tests
4. Assignment
5. Resources

Checklist:

- [x]  I have made this from my own
- [x]  I have taken help from some online resourses
- [x]  My code follows the style guidelines of this project
- [x]  I have performed a self-review of my own code
- [x]  I have taken help from some online recourses
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

screencapture-localhost-8080-2023-01-08-14_44_54

### CODE REVIEW

**Comment by siddhi-244** [comment]
> screencapture-localhost-8080-2023-01-08-14_44_54
> 
> University Managemnet system :
> 
> I have made a website which enables univerities or schools to manage their academic activities. It is website with simple UI to ease the acess of management. There are certain feautures in the website as:
> 
> 1. Attendance
> 2. Notice
> 3. Tests
> 4. Assignment
> 5. Resources

Please link the issue !

**Comment by zugzwang03** [comment]
Link the issue, also improve the name of your PR, better replace it with "university management system" @sarasiddiquie

**Comment by sarasiddiquie** [comment]
> Link the issue, also improve the name of your PR, better replace it with "university management system" @sarasiddiquie

Okay sure I'll do it

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
Please don't commit node modules

**Comment by TusharKesarwani** [comment]
Only front-end projects made using HTML, CSS and JS are accepted

**Pull request closed without merging**
