### PR TITLE
PDF MERGER 

### PR DESCRIPTION
**Pull request by yashkhandelwal2203**
# Description

This project helps us to merge two pdfs which is one of the most common task in todays digitalised world where while filling any form or application various pdf are needed to be combined .
Here basically you will be able to merge the pdfs that you want to combine and download them for future use  .

Following Dependencies were  used : 

"dependencies": {
    "express": "^4.18.2",
    "multer": "^1.4.5-lts.1",
    "pdf-merger-js": "^4.2.0",
    "pdf-parse": "^1.1.1"
  }

- [x] New Project has been added

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] The title of my pull request is a short description of the requested changes.

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
SCREENSHOTS OF THE WEBSITE .
image
image

### CODE REVIEW

**Review by Arun9739 — CHANGES_REQUESTED** [review]
Plz give a proper title, add proper content in readme. Also explain what changes you have done.

**Comment by yashkhandelwal2203** [comment]
> Plz give a proper title, add proper content in readme. Also explain what changes you have done.
I have made a new project on pdf merger technique where anyone will be able to merge and download pdfs . Title and readme files has been changed . Kindly see . Thanks

**Review by Vanshiii203 — CHANGES_REQUESTED** [review]
Mention the issue that you have resolved.
remove the folder of ingredient based recipes

**Comment by yashkhandelwal2203** [comment]
> Mention the issue that you have resolved. remove the folder of ingredient based recipes

Issue no #668 has been resolved .
The folder of ingredient based recipes has been removed .
Thanks

**Review by Arun9739 — APPROVED** [review]

**Comment by TusharKesarwani** [comment]
Mention issue number

**Comment by yashkhandelwal2203** [comment]
> Issue no #668

**Pull request closed without merging**
