### PR TITLE
live compass  #252

### PR DESCRIPTION
**Pull request by Harshit-Raj-14**
Live Compass Project

tech stack - HTML CSS JavaScript

issue : #252 

Description - A compass that tells where you are heading and a speedometer that tells at which speed you are moving.

Added description and website photo.

Please merge

### CODE REVIEW

**Comment by LiQuiD-404** [comment]
@Harshit-Raj-14 Kindly link your PR with your issue using `Closes #Issue_Number`

**Comment by Harshit-Raj-14** [comment]
@LiQuiD-404 

Closes #252

**Comment by TusharKesarwani** [comment]
The project is not working and also not responsive

**Comment by Harshit-Raj-14** [comment]
@TusharKesarwani Okay, I made the changes can you please review it again

**Comment by TusharKesarwani** [comment]
The project is not working as expected @Harshit-Raj-14

**Pull request closed without merging**
