### PR TITLE
Deploy Tutorial Blog Site

### LINKED ISSUE #380: Tutorial Documentation Website
## **Describe the project**
A website that displays the documentation/tutorial of any technical skills[EX: TutorialsPoint,JavaPoint, etc]

## Issue Type:
- [x] New Project

### PR DESCRIPTION
**Pull request by amelia2802**
## 🛠️ Issue (Number)

Closes #380 

# Description

A website that displays the documentation/tutorial of any technical skills[EX: TutorialsPoint,JavatPoint, etc]
## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] The title of my pull request is a short description of the requested changes.

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
LINK: https://codepen.io/amelia2802/full/WNKJPQB

### DESKTOP VIEW:
desk view

### Mobile VIEW:
mobile view

### CODE REVIEW

**Review by zugzwang03 — CHANGES_REQUESTED** [review]
The search functionality is not working in the website, therefore it becomes only a HTML tutorial and not exactly of any technical skills.

**Comment by amelia2802** [comment]
> The search functionality is not working in the website, therefore it becomes only a HTML tutorial and not exactly of any technical skills.

Hello @zugzwang03 , the site is not dynamic and the search bar is a demo as I haven't implemented the search functionality. So I guess it's not a bug?

**Comment by abhilipsasahoo03** [comment]
> > The search functionality is not working in the website, therefore it becomes only a HTML tutorial and not exactly of any technical skills.
> 
> Hello @zugzwang03 , the site is not dynamic and the search bar is a demo as I haven't implemented the search functionality. So I guess it's not a bug?

Hi @amelia2802 if you want to create a website tutorial such as W3School clone, try to incorporate at least the smallest dynamic components as well, otherwise it would be no better than a HTML webpage, since there's no extraordinary CSS to involve.

**Review by abhilipsasahoo03 — CHANGES_REQUESTED** [review]
I agree with @zugzwang03's suggestion. Please make the required changes.

**Pull request closed without merging**
