### PR TITLE
added the code for random meme generator

### PR DESCRIPTION
**Pull request by deep-poharkar**
This meme generator is made using HTML CSS Javascript and reddit api.

### CODE REVIEW

**Review by Vanshiii203 — CHANGES_REQUESTED** [review]
Please add a README.md file in the project with the explanation of your project, tech stack used, and screenshot of the project.
Also, link the issue with the PR

**Comment by deep-poharkar** [comment]
#167

**Comment by Vanshiii203** [comment]
@deep-poharkar please add a screenshot of your project in the readme file and a demo video to your PR

**Comment by deep-poharkar** [comment]
added the screenshot and here is the link to screen recording https://drive.google.com/file/d/1z8yDH92HxuWGUPruD9FCvtg81oB1cz1b/view?usp=sharing

**Review by harshit-paneri — APPROVED** [review]
Great Work @deep-poharkar ✨

**Comment by TusharKesarwani** [comment]
Delete screen recording from the folder

**Comment by deep-poharkar** [comment]
> Delete screen recording from the folder

done!

**Comment by TusharKesarwani** [comment]
Your project is not working

**Comment by TusharKesarwani** [comment]
Screenshot

**Comment by deep-poharkar** [comment]
> Screenshot

can you recheck now i changed the api path

**Review by TusharKesarwani — APPROVED** [review]

**Pull request merged**
