### PR TITLE
Ingredients based Recipe Search Website

### PR DESCRIPTION
**Pull request by yashkhandelwal2203**
## 🛠️ Issue (Number)

Closes #

# Description

Please include a summary of the change. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ ] I have made this from my own
- [ ] I have taken help from some online resourses 
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] The title of my pull request is a short description of the requested changes.

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Comment by yashkhandelwal2203** [comment]
Kindly See My project and check whether changes are required or not.

**Review by Vanshiii203 — COMMENTED** [review]
link the issue with the PR( using #issuenumber)

**Comment by yashkhandelwal2203** [comment]
#494 Kindly See My project and check whether changes are required or not.

**Comment by Vanshiii203** [comment]
@yashkhandelwal2203 This project is already present in the repo(https://github.com/TusharKesarwani/Front-End-Projects/tree/main/Projects/Recipe%20Finder). Do not directly raise a PR. Create an issue and wait until it is assigned to you, after that you can raise a PR,

**Pull request closed without merging**
