### PR TITLE
ZAMBO-food in the way ( food delivery website )

### PR DESCRIPTION
**Pull request by Manishkr1007**
## 🛠️ Issue (#974)

# Description

This is the food delivery website with morden Need .

## Type of change

e delete options that are not relevant.And in order to tick the check box just add x inside them for example [x] like this----->
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update
Screenshot (34)

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Review by TusharKesarwani — CHANGES_REQUESTED** [review]
Changed the name of the folder according to your project
And also remove unwanted files from the folder like *.c files

**Review by Manishkr1007 — COMMENTED** [review]
i solved all the bugs

**Comment by TusharKesarwani** [comment]
Do not add projects created by others

**Comment by Manishkr1007** [comment]
I made this project by own not this is the my project
@TusharKesarwani

**Pull request closed without merging**
