### PR TITLE
Age calculator using javascript

### PR DESCRIPTION
**Pull request by alisha722**
Age calculator using html , css and javascript .
#150 
age

### CODE REVIEW

**Comment by harshit-paneri** [comment]
Hey @alisha722 , Please add screenshot of your website

**Comment by alisha722** [comment]
> Hey @alisha722 , Please add screenshot of your website

Done !!

**Review by Vanshiii203 — CHANGES_REQUESTED** [review]
Hey @alisha722 Please attach the screenshot of the project in the readme in correct format.

**Comment by harshit-paneri** [comment]
> > Hey @alisha722 , Please add screenshot of your website
> 
> Done !!

Good

**Review by harshit-paneri — APPROVED** [review]
Good Work @alisha722 , you can try more CSS effect for good UI.

**Comment by alisha722** [comment]
> Hey @alisha722 Please attach the screenshot of the project in the readme in the correct format. Everything else appears to be in order. Great job!

Yes , I have done it . Please have a look . Thankyou !!!

**Comment by alisha722** [comment]
> Good Work @alisha722 , you can try more CSS effect for good UI.

Thankyou so much ! Will try for sure .

**Review by Vanshiii203 — APPROVED** [review]

**Comment by alisha722** [comment]
> > > Hey @alisha722 , Please add screenshot of your website
> > 
> > 
> > Done !!
> 
> Good

Thankyou.

**Review by Vanshiii203 — CHANGES_REQUESTED** [review]
Please create a separate PR for the chat bot 
Do not add it with this PR

**Review by Rishikavishnoi — APPROVED** [review]

**Review by Vanshiii203 — APPROVED** [review]

**Review by TusharKesarwani — APPROVED** [review]

**Pull request merged**
