### PR TITLE
Countify

### LINKED ISSUE #455: Countify
## **Describe the project**
It count each word and character  of a sentence.

## Issue Type:
- [x] New Project

## **Additional context**
Use HTML5,CSS3,JS.

## **Screenshots**

Screenshot (27)

### PR DESCRIPTION
**Pull request by Diptamoy-Mitra**
## 🛠️ Issue (Number)

Closes #455 

# Description
Its a application which can show each charecter and word of a sentence when anyone type.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] The title of my pull request is a short description of the requested changes.

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
     https://diptamoy-mitra.github.io/Words_charecter_counter/
Screenshot (27)

### CODE REVIEW

**Comment by Diptamoy-Mitra** [comment]
Kindly approve my PR

**Review by zugzwang03 — APPROVED** [review]
LGTM

**Comment by Diptamoy-Mitra** [comment]
@zugzwang03   Now after Approved, can i submit this project in devfolio???

**Review by zugzwang03 — APPROVED** [review]

**Comment by zugzwang03** [comment]
> @zugzwang03 Now after Approved, can i submit this project in devfolio??? please tell further process, I am beginner in open source

Wait till it gets merged

**Comment by TusharKesarwani** [comment]
Screenshot
Fix the bug

**Comment by Diptamoy-Mitra** [comment]
> i fix it please review it.
> 
> #picture:- Screenshot (28)

@TusharKesarwani  pls review it

**Pull request merged**
