### PR TITLE
[SSoC 2.0] Lorem Ipsum Generator Completed

### LINKED ISSUE #1728: [SSoC 2.0] Lorem Ipsum Generator Website
## **Describe the project**
Title - Lorem Ipsum Generator Website
Tech using - HTML, CSS and JS

## Issue Type:

- [x] New Project

## **Additional context**
- Enter the number of paragraphs, you want to generate.
- Project will provide the paragraphs.
- Copy the paragraphs and use them.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

### PR DESCRIPTION
**Pull request by Avdhesh-Varshney**
## 🛠️ Issue (Number) - 1728

Closes #1728 

# Description
- This project can generate random written paragraphs

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] The title of my pull request is a short description of the requested changes.

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
Lorem-Ipsum-Generator

### CODE REVIEW

**Comment by Avdhesh-Varshney** [comment]
@TusharKesarwani @harshit-paneri @zugzwang03 sir, please review this pull request.

Sir, this webcam video is not pulling in my system. This shows error as 
```
error: invalid path 'Projects/BuyMeaCoffee/public/Screencast from 04-07-23 09:37:48 PM IST.webm'
```

But sir, i will send it with renaming that file.

**Review by TusharKesarwani — CHANGES_REQUESTED** [review]
Not generating paragraphs according to instructions

**Comment by Avdhesh-Varshney** [comment]
https://github.com/TusharKesarwani/Front-End-Projects/assets/114330097/a5f19378-1731-4768-af00-400147072167

<br>
@TusharKesarwani sir, please again review this pr

**Comment by Avdhesh-Varshney** [comment]
@TusharKesarwani sir, please merge this pr

**Review by TusharKesarwani — APPROVED** [review]

**Pull request merged**
