### PR TITLE
Postman Clone

### PR DESCRIPTION
**Pull request by Harikaraja**
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ ] I have made this from my own
- [ ] I have taken help from some online resourses 
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [X] The title of my pull request is a short description of the requested changes.

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Comment by harsh5902** [comment]
Why is quote generator here??

**Comment by Harikaraja** [comment]
Sir I think it was merged how to remove it sir .

**Comment by harsh5902** [comment]
why you want to remove it?

**Comment by Harikaraja** [comment]
Sir it is previous projects commit accidentally I guess it was merged

**Comment by Harikaraja** [comment]
Is there any possibility to remove the quotes generator commit sir

**Comment by harsh5902** [comment]
you add the screenshots of the project first you want to merge.

**Comment by Harikaraja** [comment]
Ok sir close the pr I will open a new Pr by addi g the screenshots

**Comment by harsh5902** [comment]
sure

**Pull request closed without merging**
