### PR TITLE
Step Progress bar

### PR DESCRIPTION
**Pull request by Harikaraja**
issue number : #507

### CODE REVIEW

**Review by harshit-paneri — APPROVED** [review]
Small project but good UI

**Comment by Harikaraja** [comment]
Thank you sir

**Review by TusharKesarwani — CHANGES_REQUESTED** [review]
Remove Hex code image

**Comment by Harikaraja** [comment]
Ok sir

**Comment by Harikaraja** [comment]
Sir can please let me know how to do that I am new to git sir

**Comment by Harikaraja** [comment]
Sir made the changes mentioned .kindly check .

**Pull request merged**
