### PR TITLE
[SSoC 2.0] Video Player Project Ready

### LINKED ISSUE #1446: [SSoC 2.0] Video Player Front end project
## **Describe the project**
A clear and concise description of the project you are going to add to this repository.
- Front end project
- Creating using HTML, CSS and JS
- This project will fetch the videos from the current directory
- Enlist all the videos names in front of the user
- Asking for to play which video
- Click on that name and video will start playing
- Adding controls of sounds and screen
- Attractive background with best user interface and providing a best experience to the user

## Issue Type:

- [x] New Project

## **Additional context**
Add any other context or screenshots about the project here.
- This project will be very helpful to automate any directory to play the videos

### PR DESCRIPTION
**Pull request by Avdhesh-Varshney**
## 🛠️ Issue (Number) - 1446

Closes #1446 

# Description
- This project made by using HTML, CSS and JS
- In this project, Enter the data path of any file with extension on the javascript file in the array `currentDirVideoFiles`
- This will enlist all the video files on the webpage.
- Now, you can enjoy the video player application.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] The title of my pull request is a short description of the requested changes.

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
image

### CODE REVIEW

**Comment by Avdhesh-Varshney** [comment]
@TusharKesarwani @harshit-paneri @zugzwang03 Sirs, please review this pr

**Review by zugzwang03 — APPROVED** [review]

**Review by TusharKesarwani — APPROVED** [review]

**Comment by TusharKesarwani** [comment]
Resolve merge conflicts

**Comment by Avdhesh-Varshney** [comment]
@TusharKesarwani @zugzwang03 please again review this pr 
i have resolved the conflicts !

**Review by zugzwang03 — APPROVED** [review]

**Comment by TusharKesarwani** [comment]
Screenshot
Not working
Fix the issue

**Comment by Avdhesh-Varshney** [comment]
@TusharKesarwani sir, please again review this pr

**Comment by Avdhesh-Varshney** [comment]
@TusharKesarwani @zugzwang03 sir, i have fix the bug 4 days ago. But no action has done on this pull request. Please review this pull request.

**Comment by TusharKesarwani** [comment]
Not working

**Comment by Avdhesh-Varshney** [comment]
https://github.com/TusharKesarwani/Front-End-Projects/assets/114330097/cc12e4e2-620e-4c20-b6f3-374cd774cdd6

<br>

@TusharKesarwani @zugzwang03 @harshit-paneri sir, please again review this pull request.

I can add so many videos in this project but this will increase the size of the repository.

**Review by TusharKesarwani — APPROVED** [review]

**Comment by TusharKesarwani** [comment]
Resolve merge conflicts

**Comment by Avdhesh-Varshney** [comment]
> Resolve merge conflicts

@TusharKesarwani sir, conflicts resolved please again review this pr.

**Review by TusharKesarwani — APPROVED** [review]

**Pull request merged**
