### PR TITLE
QR Code Reader

### LINKED ISSUE #1246: Building a QR Code Reader
## Hey @TusharKesarwani I am planning to build a <i> QR code reader </i> through ReactJS.
* We can use the npm module html5-qrcode which is a lightweight library. 
* It is easily integrated with the pre-existing code. It has a real-time application that users can use very efficiently.
* Therefore, if possible, assign me this project and I will start working on it asap.

### PR DESCRIPTION
**Pull request by Swap-Nova**
## 🛠️ Issue (Number)
Closes #1246 

## Description 
Built a QR Code scanner that upon scanning the QR code either by upload or by web-cam access provides the link
of the domain site.

## Type of Change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:
- [x] I have made this from my own
- [x] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code 
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Review by harshit-paneri — COMMENTED** [review]
Issue number, Please attach issue also.

**Comment by Swap-Nova** [comment]
I am sorry I could not understand. May you share an example by taking reference of my PR?

**Comment by Swap-Nova** [comment]
Hey @harshit-paneri, I have made the changes as you said. Do review the PR.

**Comment by harshit-paneri** [comment]
> Hey @harshit-paneri, I have made the changes as you said. Do review the PR.

Yes but please share the assigned issue

**Comment by harshit-paneri** [comment]
Did you created any issue for this PR?

**Comment by Swap-Nova** [comment]
Yes, the issue was #1246 which I had created and was assigned to work upon.

**Comment by Swap-Nova** [comment]
Screenshot 2023-06-24 at 1 25 12 AM

**Comment by harshit-paneri** [comment]
image
Deployed page is blank

**Review by harshit-paneri — CHANGES_REQUESTED** [review]
Demo link is not working, Please check it.

**Comment by Swap-Nova** [comment]
How do I deploy the application from a PR?

**Comment by harshit-paneri** [comment]
> How do I deploy the application from a PR?

check you code.. Is it working?

**Comment by Swap-Nova** [comment]
Yeah, I tried it in my live server. It was working as I expected it to.

**Comment by harshit-paneri** [comment]
> Yeah, I tried it in my live server. It was working as I expected it to.

send SS

**Comment by Swap-Nova** [comment]
Is it because it uses an npm module?

**Comment by Swap-Nova** [comment]
Screenshot 2023-06-24 at 1 39 50 AM

**Comment by Swap-Nova** [comment]
> > Is it because it uses an npm module?
> 
> only HTML , CSS and JS projects are allow

But actually, this project required a library to run.

**Comment by harshit-paneri** [comment]
> > > Is it because it uses an npm module?
> > 
> > 
> > only HTML , CSS and JS projects are allow
> 
> But actually, this project required a library to run.

I understand but React and node projects are not allow

**Comment by Swap-Nova** [comment]
Let me check an alternative. I am sure we can directly use an script file instead.

**Comment by harshit-paneri** [comment]
> > > Is it because it uses an npm module?
> > 
> > 
> > only HTML , CSS and JS projects are allow
> 
> But actually, this project required a library to run.

@TusharKesarwani please check.

**Review by harshit-paneri — APPROVED** [review]
Now it is working !!!

**Comment by Swap-Nova** [comment]
All Good now, right?

**Comment by Swap-Nova** [comment]
> Now it is working !!!

Great, thanks for the help.

**Review by TusharKesarwani — APPROVED** [review]

**Pull request merged**
