### PR TITLE
Sales management Dashboard UI

### LINKED ISSUE #419: Management dashboard UI
## **Describe the project**
I want to design a sales management dashboard user interface . I want to create an attractive and clear minimal looking dashboard UI which can be used in sales management website 

## Issue Type:
- [x] New Project

## **Additional context**
I will create it using html , css and js .

## **Screenshots**

- If applicable, add screenshots to help explain your problem.
dashboards_by_function_it_project_management_dashboard_slide01

### PR DESCRIPTION
**Pull request by alisha722**
## 🛠️ Issue 419

Closes #419 

# Description
I have designed a simple yet attractive UI for dashboard template of sales management . I have choosen a minimal theme for it . It has light and dark mode as well it is responsive .

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] The title of my pull request is a short description of the requested changes.

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

https://user-images.githubusercontent.com/84632701/215169966-502ae7e9-854d-4f80-a3c1-5587cdb578f2.mp4

### CODE REVIEW

**Review by Vanshiii203 — CHANGES_REQUESTED** [review]
remove the horizontal scroll 
image

**Comment by alisha722** [comment]
> remove the horizontal scroll image

yes , I have done that . Please check .

**Review by Vanshiii203 — CHANGES_REQUESTED** [review]
image
there is some extra margin on the left because of which the whole thing is shifted to the right and is overflowing.
fix it

**Comment by alisha722** [comment]
> image there is some extra margin on the left because of which the whole thing is shifted to the right and is overflowing. fix it

Yes I have rectified that and created a new pull request for the same .Please have a look . Thankyou .

**Pull request closed without merging**
