### PR TITLE
Space Tourism Website #534

### PR DESCRIPTION
**Pull request by amajaying**
🛠️ Issue (Number)
Closes https://github.com/TusharKesarwani/Front-End-Projects/issues/534

Description
This is a landing page for Space Tourism

Checklist:
✅ I have made this from my own
✅ My code follows the style guidelines of this project
✅ I have performed a self-review of my own code

image
image

ISSUE #534

### CODE REVIEW

**Comment by harsh5902** [comment]
tell me in brief what does this website do?

**Comment by amajaying** [comment]
> tell me in brief what does this website do?

This website is basically Universe themed, containing information about different moons/planets/comets in the universe. 

For now, this website has only few infos, will be adding more in coming time.

**Comment by harsh5902** [comment]
@TusharKesarwani look in this matter as it is just an information website.

**Comment by amajaying** [comment]
> @TusharKesarwani look in this matter as it is just an information website.

Sorry, @harsh5902 I may be unknown of this. Is there any preset requirement to what a project can be or not? 
Please let me know.

**Review by harsh5902 — APPROVED** [review]

**Comment by harsh5902** [comment]
add more info in this project

**Comment by amajaying** [comment]
> add more info in this project

Sure, will add few more features in this site till SWOC ends. Could you please add, "Ready to merge" and "SWOC" labels in this? Thanks :)

**Pull request merged**
