### PR TITLE
Improvement In Password generator

### PR DESCRIPTION
**Pull request by Harikaraja**
issue number: #353

### CODE REVIEW

**Review by Vanshiii203 — CHANGES_REQUESTED** [review]
Please remove the folder of Caesar cipher

**Comment by Harikaraja** [comment]
Mam i didn't understand

**Comment by Harikaraja** [comment]
Actually that was accepted by you today afternoon.It is not yet merged

**Comment by LiQuiD-404** [comment]
@Harikaraja You have added the Ceaser Cipher project as well in this PR. Kindly remove it

**Comment by Harikaraja** [comment]
Sir how to do that please let me know I am new to git

**Pull request closed without merging**
