### PR TITLE
Adding the budget Manager

### PR DESCRIPTION
**Pull request by Aarsh30**
## **Describe the project**
A comprehensive and user-friendly tool to track, manage, and optimize your finances. Effortlessly monitor income, expenses, budgets, and savings goals. Gain insights through intuitive visualizations and generate financial reports. Achieve financial freedom and make informed decisions with this powerful personal finance management solution.

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

## **Screenshots**
image

### CODE REVIEW

**Comment by zugzwang03** [comment]
update your branch

**Comment by Aarsh30** [comment]
> update your branch

i had update it

**Comment by zugzwang03** [comment]
not updated

**Comment by Aarsh30** [comment]
> not updated

done i have update it now

**Review by zugzwang03 — APPROVED** [review]

**Review by TusharKesarwani — CHANGES_REQUESTED** [review]
Remove .vscode folder

**Comment by Aarsh30** [comment]
> Remove .vscode folder

yaa @TusharKesarwani  i had remove that vs code folder

**Review by TusharKesarwani — APPROVED** [review]

**Pull request merged**
