### PR TITLE
Advice generator app by Shefali

### PR DESCRIPTION
**Pull request by WebdevShefali**
Issue No. #1337 

# Description

Added a advice generator app created using HTML, CSS, JavaScript and API.

# Checklist:

- [x ] I have made this from my own
- [ ] I have taken help from some online resourses 
- [ ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] The title of my pull request is a short description of the requested changes.

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
Screenshot (460)

### CODE REVIEW

**Review by zugzwang03 — APPROVED** [review]

**Comment by TusharKesarwani** [comment]
Mention the issue number

**Comment by WebdevShefali** [comment]
> Mention the issue number

Added the issue number

**Comment by TusharKesarwani** [comment]
> > Mention the issue number
> 
> Added the issue number

That's not a issue number

**Comment by WebdevShefali** [comment]
> > > Mention the issue number
> > 
> > 
> > Added the issue number
> 
> That's not a issue number

Added the issue

**Comment by zugzwang03** [comment]
> > > > Mention the issue number
> > > 
> > > 
> > > Added the issue number
> > 
> > 
> > That's not a issue number
> 
> Added the issue
That is the PR number you tagged, tag your issue number correctly, so that when you hover, you can get the correct issue.

**Comment by WebdevShefali** [comment]
> 

Now I've added the right issue number

**Review by TusharKesarwani — APPROVED** [review]

**Pull request merged**
