### PR TITLE
[SSoC 2.0] Alarm Clock

### LINKED ISSUE #1713: Alarm Clock using JavaScript
## **Describe the project**
This project helps to create an alarm clock. The user can set an alarm that rings at the time set by the user and can be switched off. It also has a digital clock to show the current time. Easy and beginner friendly project using HTML, CSS and JavaScript.

## Issue Type:
- [x] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**
image
image

### PR DESCRIPTION
**Pull request by Abhilasha-Sagar**
## 🛠️ Issue (1713)

Closes #1713

# Description

This project helps to create an alarm clock. The user can set an alarm that rings at the time set by the user and can be switched off. It also has a digital clock to show the current time. Easy and beginner-friendly project using HTML, CSS, and JavaScript.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] My changes generate no new warnings
- [x] The title of my pull request is a short description of the requested changes.

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
image
image
image

### CODE REVIEW

**Comment by Abhilasha-Sagar** [comment]
@TusharKesarwani @zugzwang03 Please review this PR.

**Review by zugzwang03 — CHANGES_REQUESTED** [review]
add readme

**Comment by Abhilasha-Sagar** [comment]
@zugzwang03 Added readme

**Review by Abhilasha-Sagar — COMMENTED** [review]
Added readme.md

**Review by zugzwang03 — APPROVED** [review]

**Review by TusharKesarwani — APPROVED** [review]

**Pull request merged**
