### PR TITLE
A Drawing App-Sketch It #106

### LINKED ISSUE #106: A drawing app
Using this app,users can be able to draw using different geometrical shapes,also can save their work to their local system.

### PR DESCRIPTION
**Pull request by tejasri415**
## 🛠️ Issue (106)

Closes #106 

# Description

 I have designed a simple drawing website which makes user to draw different shapes using diffrent colors and can save the work to their local machine.

## Type of change

 
- [x] New feature (non-breaking change which adds functionality)
 
# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] The title of my pull request is a short description of the requested changes.

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
landing
drawing

### CODE REVIEW

**Review by LiQuiD-404 — CHANGES_REQUESTED** [review]
@tejasri415 Kindly add a Readme.md file and add your project's description, the tech stack used, and some screenshots of the same.

**Review by Vanshiii203 — CHANGES_REQUESTED** [review]
Add a readme.md file for your project

**Comment by tejasri415** [comment]
@Vanshiii203  @LiQuiD-404 I added readme file,kindly check it

**Review by Vanshiii203 — CHANGES_REQUESTED** [review]
make it responsive

**Comment by tejasri415** [comment]
@Vanshiii203  I've made it responsive,please approve and merge my PR.

**Review by LiQuiD-404 — APPROVED** [review]
LGTM ✨

**Comment by tejasri415** [comment]
> LGTM ✨

Thankyou for your Approval sir

**Comment by tejasri415** [comment]
@LiQuiD-404  sorry for requesting review again sir, I clicked it by mistake,my apologies sir

**Comment by tejasri415** [comment]
@Vanshiii203 @LiQuiD-404 kindly approve my PR please

**Comment by tejasri415** [comment]
@Vanshiii203 @LiQuiD-404 I request you to please approve my PR,it's been many days 😥

**Review by LiQuiD-404 — APPROVED** [review]
LGTM.

**Review by Vanshiii203 — APPROVED** [review]

**Comment by Vanshiii203** [comment]
The responsiveness can still be improved

**Pull request merged**
