### PR TITLE
added age calculator 

### LINKED ISSUE #1481: Age generator
## **Describe the project**
A clear and concise description of the project you are going to add to this repository.
I m going to create an age calculator. As you can see from the final version of the project, we have a container here with the title age calculator with an input of a date. If we click on the date input, we can choose the date of our birthday. For example, if we choose a date in in 2022 and if we click now on Calculate Age, you can see the age is calculated based on this date and saying your age is 21 years old.
## Issue Type:
- [x] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

### PR DESCRIPTION
**Pull request by SimranLahrani842**
## 🛠️ Issue (Number)
Closes #1481 

# Description

Please include a summary of the change. Please also include relevant motivation and context. List any dependencies that are required for this change.
Added age calculator.Just select your dob from  calendar and click on button ,it will calculate and display the current age.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] The title of my pull request is a short description of the requested changes.

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
op1

### CODE REVIEW

**Comment by SimranLahrani842** [comment]
> This issue is not assign to you.

How sir?

**Comment by harshit-paneri** [comment]
> > This issue is not assign to you.
> 
> Why sir?

image

**Comment by harshit-paneri** [comment]
Wait, I will assign you don't woryy.

**Review by harshit-paneri — APPROVED** [review]

**Comment by SimranLahrani842** [comment]
> Wait, I will assign you don't worry.

Thankyou sir please approve and merge my pr @TusharKesarwani

**Comment by TusharKesarwani** [comment]
Project is already present in the repo

**Pull request closed without merging**
