### PR TITLE
Harika

### PR DESCRIPTION
**Pull request by Harikaraja**

### CODE REVIEW

**Comment by LiQuiD-404** [comment]
@Harikaraja Kindly add a description of your project and screenshot of the same in this chat. Also make a Readme.md file which should consist of the project description, tech stack used, screenshot/demo video. Also remove the settings.json file of Tic Tac Toe and Password Generator projects from your PR.

**Review by LiQuiD-404 — CHANGES_REQUESTED** [review]
@Harikaraja  Kindly make the mentioned changes.

**Comment by Harikaraja** [comment]
Sir where do I need to add the project description and screen shot

**Comment by LiQuiD-404** [comment]
@Harikaraja No need to call me sir. It's Shubham. Make a Readme.md file and add the project description there and add some reference image like screenshot of the project in that Readme. Also add that screenshot here in the chat. This will help me review your project faster.

**Comment by Harikaraja** [comment]
Sure, will do that.

**Comment by Harikaraja** [comment]
Added README.md and made all the specified changes

**Pull request closed without merging**
