### PR TITLE
Create Tribute Page

### LINKED ISSUE #1205: Tribute page
Hi  @TusharKesarwani @zugzwang03.I am a contributor in SSOC 23. I want to add a new project in this repository. A tribute page which I will create using HTML, CSS and JavaScript. Please assign this task under label SSOC 23 to me.

### PR DESCRIPTION
**Pull request by vipulbhalewar**
## 🛠️ Issue (Number) I want to add my own project in this repository.

Closes #1205 

# Description

Please include a summary of the change. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] The title of my pull request is a short description of the requested changes.

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Comment by vipulbhalewar** [comment]
Created Tribute Page with the Help of HTML and CSS Language.

http://127.0.0.1:5500/index.html

@zugzwang03 @TusharKesarwani have a look into it and merge it.

**Review by zugzwang03 — CHANGES_REQUESTED** [review]
You did not make any changes in the files, where is the project?

**Comment by vipulbhalewar** [comment]
I had made my own project Tribute page that I want to add in the project section.

https://github.com/vipulbhalewar/OIBSIP2/blob/main/Tribute%20Page/index.html

Please check this once @zugzwang03 @TusharKesarwani

**Comment by zugzwang03** [comment]
You can improve the margin though, and add some more CSS to make it look nicer, otherwise its fine. Also if you can include some JS work into it, it would be good, think about innovating it further.

**Comment by vipulbhalewar** [comment]
Okay I will do that. Also, can you please attach this project under project section.

**Comment by zugzwang03** [comment]
> 

I cannot attach the project. It is your PR, so you have to make the changes, see how others did it, follow accordingly.

**Comment by vipulbhalewar** [comment]
Ohh okay.

**Pull request closed without merging**
