### PR TITLE
Added Simon game

### LINKED ISSUE #320: Simon Game
Hey, @TusharKesarwani I want to add the Simon game to your repo which is completely designed by me. Please assign me this issue. Thank you!

- Screenshot:-
Screenshot (549)

### PR DESCRIPTION
**Pull request by sumitkr2000**
## 🛠️ Issue (Number)

Closes #320 

# Description

I have added the Simon game to the front-end project it is completely designed by me. Please review my pr and merge it. Thank you!

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] The title of my pull request is a short description of the requested changes.

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
simon

### CODE REVIEW

**Review by LiQuiD-404 — CHANGES_REQUESTED** [review]
Please link your PR with your Issue. Do not include the quotes. Closes #Issue_Number

**Comment by sumitkr2000** [comment]
No check @LiQuiD-404

**Comment by LiQuiD-404** [comment]
@sumitkr2000 It has not been linked. Closes #320

**Review by Vanshiii203 — APPROVED** [review]
LGTM!

**Comment by sumitkr2000** [comment]
LGTM??

**Comment by sumitkr2000** [comment]
Now check @LiQuiD-404

**Comment by sumitkr2000** [comment]
Now check @LiQuiD-404

**Comment by LiQuiD-404** [comment]
@sumitkr2000 LGTM ✨

**Review by LiQuiD-404 — APPROVED** [review]
@sumitkr2000 LGTM ✨

**Comment by sumitkr2000** [comment]
What does LGTM mean??

**Comment by sumitkr2000** [comment]
@TusharKesarwani Please merge my pr

**Comment by LiQuiD-404** [comment]
@sumitkr2000 LGTM means Looks good to me. Your PR will soon be merged.

**Comment by TusharKesarwani** [comment]
A similar game already exists in the repo

**Comment by sumitkr2000** [comment]
Where is it I cant see it?? @TusharKesarwani

**Comment by sumitkr2000** [comment]
Where is it I cant see it?? @TusharKesarwani

**Pull request closed without merging**
