### PR TITLE
updated and changed the required code for adding transitions. 

### LINKED ISSUE #1191: Incorporating  using visually appealing transitions or animations when the user interacts with the form.
Apply subtle hover effects to interactive elements, such as buttons or input fields, to provide visual feedback to the user.
For instance, when the user hovers over the sign-in button, it could change color, scale slightly, or have a shadow effect.

The solution I would like is to apply subtle hover effects to interactive elements, such as buttons or input fields, in order to provide visual feedback to the user. This can be achieved by implementing animations or changes in appearance when the user hovers over these elements. These effects should be visually appealing and help the user understand that the element is interactive or clickable. They can include changes in color, size, shadow, or any other visual cues that indicate interactivity. The goal is to enhance the user experience and make the sign-in page more engaging and intuitive.

Some alternative solutions for applying subtle hover effects to interactive elements on a sign-in page include:

Color Change: Change the color of interactive elements when the user hovers over them, providing visual feedback.

Scale or Size Adjustment: Scale or resize the interactive elements slightly when the user hovers over them, indicating their interactivity.

Shadow Effects: Apply a subtle shadow effect to interactive elements on hover, giving them a sense of depth and interactivity.

Transition Effects: Use smooth transition animations when the user hovers over interactive elements, creating a seamless visual experience.

Button Highlight: Highlight buttons or clickable elements by changing their background color or adding an outline on hover.

Cursor Transformation: Change the cursor style to a pointer or hand icon when hovering over interactive elements, indicating their clickable nature.

### PR DESCRIPTION
**Pull request by HimanshiDafouty**
## 🛠️ Issue (#1191 )

Closes #1191

# Description

The changes made include adding visually appealing transitions to the sign-in and sign-up buttons, as well as modifying the background color of the buttons upon clicking for a more attractive and engaging user experience, while maintaining the original 3D effect and overall structure of the page.

## Type of change

- [ x] New feature (non-breaking change which adds functionality)
- [x ] This change requires a documentation update

# Checklist:

- [x ] I have made this from my own
- [ x] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ x] My changes generate no new warnings
- [ x] The title of my pull request is a short description of the requested changes.

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Comment by HimanshiDafouty** [comment]
[
[update. pdf](https://github.com/TusharKesarwani/Front-End-Projects/files/11767547/update.pdf)
](URL)

**Comment by HimanshiDafouty** [comment]
May, I know about my pull request

**Review by zugzwang03 — APPROVED** [review]

**Comment by HimanshiDafouty** [comment]
will it get merged or not , since the pull request is closed??

**Comment by zugzwang03** [comment]
it won't get merged

**Comment by HimanshiDafouty** [comment]
May , I know the reason??

**Comment by HimanshiDafouty** [comment]
Did , I made a mistake ??

**Comment by zugzwang03** [comment]
You deleted the branch and closed the PR
Raise a new one please

**Comment by HimanshiDafouty** [comment]
sure. 
Thank you for telling me

**Pull request closed without merging**
