### PR TITLE
Adding footer and login/ SignUp page in "Villa Hotel"

### PR DESCRIPTION
**Pull request by KritikaRawat**
Closes Issue Number #867 

# Description

Please include a summary of the change. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Type of change
Added Login/Signup Page
Added Footer

- [X] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality not to work as expected)

# Checklist:

- [X] I have made this from my own
- [X] I have taken help from some online resources 
- [X] My code follows the style guidelines of this project
- [X] I have commented on my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings
- [X] The title of my pull request is a short description of the requested changes.

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
WhatsApp Image 2023-06-18 at 23 42 49

WhatsApp Image 2023-06-18 at 23 42 18

### CODE REVIEW

**Comment by zugzwang03** [comment]
update your branch.

**Comment by zugzwang03** [comment]
I think it is already too late, you need to squash the commits in this PR and raise a new PR for the updated changes.

**Comment by KritikaRawat** [comment]
I have updated the branch

**Review by zugzwang03 — CHANGES_REQUESTED** [review]
remove .vscode

**Review by zugzwang03 — APPROVED** [review]

**Review by TusharKesarwani — APPROVED** [review]

**Pull request merged**
