### PR TITLE
Netflix landing page clone

### LINKED ISSUE #1150: Netflix Landing Page Clone
## **Describe the project**
Netflix landing page clone using HTML and CSS.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**
This website is responsive for mobile devices.

## **Screenshots**

Screenshot (2)
Screenshot (3)

### PR DESCRIPTION
**Pull request by champati-v**
## 🛠️1150

Closes #1150 

# Description
A clone of Landing page of a popular OTT platform - Netflix.
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [x] New Project addition

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
Screenshot (3)

Screenshot (2)
Screenshot (5)

Screenshot (8)

Screenshot (9)

Screenshot (7)

### CODE REVIEW

**Comment by harshit-paneri** [comment]
issue is not assigned to u

**Comment by champati-v** [comment]
Hii @TusharKesarwani @harshit-paneri, apologies for making a PR without getting assigned. Can you please assign this issue to me. 
Thank you!

**Comment by harshit-paneri** [comment]
> Hii @TusharKesarwani @harshit-paneri, apologies for making a PR without getting assigned. Can you please assign this issue to me. Thank you!

okay but next time make sure you can only send PR to assigned issues

**Review by harshit-paneri — APPROVED** [review]
Approved , 
💯 Responsive

**Review by TusharKesarwani — APPROVED** [review]

**Pull request merged**
