### PR TITLE
Initial commit for snake,water & Gun game

### LINKED ISSUE #342: I would like to create a Snake,Water & Gun game
I would like to develop a game where the user and the computer plays the snake water game and the computer selects the input randomly.please assign me this task

### PR DESCRIPTION
**Pull request by Keegan-20**
🛠️ Issue (Number):
Closes #342 

# Description

It is a Snake,water &gun game which is played between the user and the computer where the computer chooses a random option and thus decides who wins the game. 

## Type of change

- [x ] New feature (non-breaking change which adds functionality)

# Checklist:

- [x ] I have made this from my own
- [ x] I have taken help from some online resourses 
- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] The title of my pull request is a short description of the requested changes.

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
swg22

### CODE REVIEW

**Review by LiQuiD-404 — CHANGES_REQUESTED** [review]
@Keegan-20 Kindly add a Readme.md file for your project.

**Review by abhilipsasahoo03 — CHANGES_REQUESTED** [review]
Add a README stating the details about the game, including Tech stack used, rules of the game, functionalities (if present like scorekeeping and stuff), etc.

**Comment by Keegan-20** [comment]
i have added readme.md file please review it

**Review by abhilipsasahoo03 — CHANGES_REQUESTED** [review]
Hi @Keegan-20 everything looks good, awesome work, but just a suggestion, could you please add a bit of Markdown formatting to make the README a bit more readable, i.e., Appropriate headings for each section with proper styling + bullet points for describing rules/steps + other stuff. 

Here's a guide to Markdown syntax, in case you want to refer to:
https://www.markdownguide.org/basic-syntax/

**Comment by Keegan-20** [comment]
> Hi @Keegan-20 everything looks good, awesome work, but just a suggestion, could you please add a bit of Markdown formatting to make the README a bit more readable, i.e., Appropriate headings for each section with proper styling + bullet points for describing rules/steps + other stuff.
> 
> Here's a guide to Markdown syntax, in case you want to refer to: https://www.markdownguide.org/basic-syntax/

Thank You @abhilipsasahoo03  for the article i have done the necessary formating.Please Review it.

**Review by abhilipsasahoo03 — APPROVED** [review]
Looks good to me! Awesome work @Keegan-20 👍

**Comment by Keegan-20** [comment]
Thank you😊

**Review by LiQuiD-404 — APPROVED** [review]
@Keegan-20 LGTM ✨

**Review by TusharKesarwani — APPROVED** [review]

**Comment by TusharKesarwani** [comment]
Screenshot
The background is not working
Fix the issue

**Comment by Keegan-20** [comment]
> Screenshot The background is not working Fix the issue

i have fixed the issue please review the same

**Review by Rishikavishnoi — APPROVED** [review]
@Keegan-20 LGTM 🎉

**Review by TusharKesarwani — APPROVED** [review]

**Pull request merged**
