### PR TITLE
Restraunt Ordering System Project

### PR DESCRIPTION
**Pull request by vaibhavx42**
## 🛠️ Issue (Number)

Closes # [688](https://github.com/TusharKesarwani/Front-End-Projects/issues/688)

# Description
- The project is based on a Utopian theme inspired by Elon Musk's vision of life on Mars in 2050.-
- The system eliminates the need for waiters in the restaurant.
- The aim is to provide an innovative and futuristic dining experience to customers.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] The title of my pull request is a short description of the requested changes.

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
image

### CODE REVIEW

**Review by Vanshiii203 — COMMENTED** [review]
This project is already present in the repo
https://github.com/TusharKesarwani/Front-End-Projects/tree/main/Projects/Restaurant-website

**Comment by vaibhavx42** [comment]
- Hey @Vanshiii203  The project I have developed encompasses both the **customer and admin sides** of a restaurant. In addition, it features a unique **3D display using webgl** that showcases the restaurant's menu items. As such, it differs from the project you previously mentioned which lacks these distinctive features .

- The mentioned project doesn't have a admin side to manage the orders and allocate the number per order/table .

- I believe that my project is unique and I am I look forward to getting it merged.

**Review by Arun9739 — CHANGES_REQUESTED** [review]
Add a Readme file describing about your project

**Comment by vaibhavx42** [comment]
- Hey @Arun9739  Thank you for suggesting the change . I wanted to let you know that I have already created a readme file and included it in the project files when I pushed the project and opened a pull request here!

- If you have any specific feedback or changes that you would like me to make to the existing readme file, I would be happy to work with you to make those revisions. Please let me know if there is anything else that I can assist you with.

- Attaching a screenshot for your refference here.

image

**Comment by vaibhavx42** [comment]
**@Arun9739 Please review the changes, Project submission deadline is approaching**

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
What are those .idea folders ? If it isn't important remove it!

**Review by vaibhavx42 — COMMENTED** [review]
- Removed

**Review by Arun9739 — APPROVED** [review]

**Review by siddhi-244 — APPROVED** [review]

**Comment by vaibhavx42** [comment]
**Can you remove that duplicate label @Vanshiii203**

**Review by zugzwang03 — APPROVED** [review]

**Pull request merged**
