### PR TITLE
added Bookmark app

### LINKED ISSUE #583: Improvement in Bookmarker Application project
**Is your feature request related to a problem? Please describe.**
The existing project delete button doesn't remove the required bookmark and it also deletes other bookmarks as well. 

**Describe the solution you'd like**
I will correct the delete button functionality and change some features of the project and UI as well.

**Describe alternatives you've considered**
N/A

**Additional context**
**Original:** As you can see delete button is removing other entries also.
ezgif com-gif-maker (1)

**Expected changes:**
ezgif com-gif-maker (2)

### PR DESCRIPTION
**Pull request by muskan467**
## 🛠️ Issue #583 

Closes #583 

# Description

I have made some changes in functionality of delete button. Improved the UI of project also.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] The title of my pull request is a short description of the requested changes.

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

Original project | Expected changes |
:---:|:---:|
 |  |

### CODE REVIEW

**Review by LiQuiD-404 — APPROVED** [review]
LGTM ✨

**Review by LiQuiD-404 — CHANGES_REQUESTED** [review]
@muskan467 The delete functionality is not working. Kindly look into it.

**Comment by muskan467** [comment]
@LiQuiD-404 I have made the requested changes, pls look into it.

**Review by Vanshiii203 — APPROVED** [review]

**Review by siddhi-244 — APPROVED** [review]

**Review by LiQuiD-404 — APPROVED** [review]
LGTM ✨

**Comment by muskan467** [comment]
@TusharKesarwani Kindly merge it

**Pull request merged**
