### PR TITLE
number guessing game using JS 

### PR DESCRIPTION
**Pull request by alisha722**
#138  
 This is a number guessing game .
no  guessing game

### CODE REVIEW

**Review by siddhi-244 — APPROVED** [review]

**Review by Vanshiii203 — CHANGES_REQUESTED** [review]
Please add a README.md file in the project with the explanation of your project, tech stack used, and screenshot of the project.

**Comment by alisha722** [comment]
I have added readme file . Please check

**Comment by Vanshiii203** [comment]
> I have added readme file . Please check
Please attach the screenshot of the project in the readme in correct format

**Comment by alisha722** [comment]
> > I have added readme file . Please check
> > Please attach the screenshot of the project in the readme in correct format

Yes I have updated it . Please have a look . Thankyou !!

**Review by Vanshiii203 — APPROVED** [review]

**Review by TusharKesarwani — APPROVED** [review]

**Pull request merged**
