### PR TITLE
A  responsive movie website

### PR DESCRIPTION
**Pull request by Roudranilk**
## 🛠️ Issue (#890)

# Description

Created a responsive movie website with links to the movies section that also shows the trailer.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (swiper.js)
- [x] Breaking change (Redirecting to every movie trailer page)

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] The title of my pull request is a short description of the requested changes.

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Comment by Roudranilk** [comment]
@TusharKesarwani  @harshit-paneri kindly review my pull request for the issue #890

**Review by TusharKesarwani — CHANGES_REQUESTED** [review]
Add only one project

**Comment by Roudranilk** [comment]
@TusharKesarwani this is one project only, the index.html is the file and other HTML files are just anchor files that is when you click a movie under movies bar it will redirect to a page.

**Review by TusharKesarwani — CHANGES_REQUESTED** [review]
Do not add movies mp4 files directly
Upload it in any other place and link it to the website

**Comment by Roudranilk** [comment]
@TusharKesarwani Uploading it on any other source might create some issues if someone tries to play it.
Can you recommend a place where I can upload them?

**Comment by TusharKesarwani** [comment]
> @TusharKesarwani Uploading it on any other source might create some issues if someone tries to play it. Can you recommend a place where I can upload them?

You can create another repository and upload all mp4 files there
And link those files here

**Comment by Roudranilk** [comment]
@TusharKesarwani I have deleted the video files and used google drive for the process, kindly check it.

**Review by TusharKesarwani — APPROVED** [review]

**Pull request merged**
