### PR TITLE
Shoe website landing page(#184)

### PR DESCRIPTION
**Pull request by nitishsadhu03**
Shoe website landing page project added to front-end-project repo and also added readme file. Kindly merge this.

#184

### CODE REVIEW

**Review by Vanshiii203 — COMMENTED** [review]
@nitishsadhu03 Can you make it responsive??

**Comment by nitishsadhu03** [comment]
@Vanshiii203 Sorry Mam but have very less knowledge and no experience on that will try to implement from the next projects after learning.

**Review by Vanshiii203 — APPROVED** [review]

**Comment by Vanshiii203** [comment]
> @Vanshiii203 Sorry Mam but have very less knowledge and no experience on that will try to implement from the next projects after learning.

No Problem😊

**Review by abhilipsasahoo03 — CHANGES_REQUESTED** [review]
Kindly elaborate on the tech stack used in your README. And I just checked to find out that the demo screenshot you have attached is not being displayed, perhaps some issue with the link?

**Comment by nitishsadhu03** [comment]
Ok will make the changes and fix the image under screenshots.

**Comment by nitishsadhu03** [comment]
Made the required changes. Kindly have a look into it.

**Comment by abhilipsasahoo03** [comment]
> Made the required changes. Kindly have a look into it.

Hello, I don't think the problem is with the extension, the problem persists with the path. Try `/images/website-screenshot.jpg` as the path. @nitishsadhu03

**Comment by nitishsadhu03** [comment]
with /images path it is not visible to me so I tried ./images path. Check now.

**Comment by TusharKesarwani** [comment]
Sorry, but non-responsive websites are not accepted in this repo

**Pull request closed without merging**
