### PR TITLE
Added Essentia - NEW PROJECT

### LINKED ISSUE #1788: [NEW PROJECT]: Essentia - Skin Care Product website
## **Describe the project**
A website for skincare products : Essentia

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project
Screenshot (63)
Screenshot (64)
Screenshot (65)

### PR DESCRIPTION
**Pull request by blindaks**
## 🛠️ Issue (Number)

Closes #1788 

# Description
Added a new project.

## Type of change
- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] The title of my pull request is a short description of the requested changes.

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Comment by blindaks** [comment]
@TusharKesarwani @harshit-paneri @zugzwang03 Please review this.

**Comment by blindaks** [comment]
@zugzwang03 Please check now.

**Review by zugzwang03 — APPROVED** [review]

**Comment by blindaks** [comment]
@TusharKesarwani Please merge this pr

**Review by TusharKesarwani — APPROVED** [review]

**Pull request merged**
