### PR TITLE
Responsivness fixed

### PR DESCRIPTION
**Pull request by rahulrana701**
#1308

# Description
I have fixed the responsivness , now it will be working fine in all devices.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
# Checklist:

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
Screenshot 2023-06-21 232345
Screenshot 2023-06-21 232300

### CODE REVIEW

**Comment by rahulrana701** [comment]
@TusharKesarwani  I have fixed the responsivness , you can review the pr

**Comment by rahulrana701** [comment]
hi @harshit-paneri  @zugzwang03 it's been 4 days now , the pr is not reviewed yet so can you please review it so that It can be merged

**Comment by zugzwang03** [comment]
resolve conflicts

**Comment by rahulrana701** [comment]
hi @zugzwang03 @harshit-paneri  done..

**Comment by rahulrana701** [comment]
@zugzwang03 @harshit-paneri can you review it now ??

**Comment by TusharKesarwani** [comment]
Screenshot
Make Size of Cards equal

**Pull request closed without merging**
