### PR TITLE
added crud

### PR DESCRIPTION
**Pull request by kuldeepjoshi27**
issue number = #236

### CODE REVIEW

**Comment by kuldeepjoshi27** [comment]
crud app

**Comment by kuldeepjoshi27** [comment]
crud 2

**Review by Vanshiii203 — CHANGES_REQUESTED** [review]
Remove the .vscode file and attach screenshot of project in readme.md file

**Review by kuldeepjoshi27 — COMMENTED** [review]
crud app
crud 2

**Review by harshit-paneri — CHANGES_REQUESTED** [review]
Please add more description in Readme file

**Pull request closed without merging**
