### PR TITLE
added youtube clone

### LINKED ISSUE #1080: New Project : Youtube Clone [SSOC'23]
## **Describe the project**
I want to add a youtube clone that shows videos from different channels and displays it in a youtube fashion design
## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Screenshots**

image

Please assign me this Issue under SSOC'23

### PR DESCRIPTION
**Pull request by Swapnil-Singh-99**
## 🛠️ Issue (1080)

Closes #1080 

# Description

I have added a Youtube Clone that uses Rapid API for fetching Video Data and displaying on the webpage

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] The title of my pull request is a short description of the requested changes.

# ATTACH SCREEN-SHOTS
image

# DEPLOYMENT LINK
[View Live](https://youtobe-clone.onrender.com/)

### CODE REVIEW

**Comment by Swapnil-Singh-99** [comment]
@TusharKesarwani Please review and merge this PR under SSOC'23

**Review by zugzwang03 — CHANGES_REQUESTED** [review]
you have to add project files here, not submodules

**Comment by Swapnil-Singh-99** [comment]
> you have to add project files here, not submodules

Sir what this means can you explain me.
I am not familiar with this

**Comment by zugzwang03** [comment]
image
you don't have files added here, you have to add files to the repository.

**Comment by Swapnil-Singh-99** [comment]
@zugzwang03 I have made a new PR please Review
https://github.com/TusharKesarwani/Front-End-Projects/pull/1375

And close this PR

**Pull request closed without merging**
