### PR TITLE
Adding Color Selection Option in hexcode Generator

### PR DESCRIPTION
**Pull request by Harikaraja**
issue number : #463

### CODE REVIEW

**Review by Vanshiii203 — CHANGES_REQUESTED** [review]
update the screenshot with your changes in the readme file

**Comment by Harikaraja** [comment]
Done mam . I have added the screen shots .please check

**Comment by Vanshiii203** [comment]
@Harikaraja delete the old screenshot

**Comment by Harikaraja** [comment]
Done mam please check

**Review by Vanshiii203 — APPROVED** [review]

**Review by TusharKesarwani — APPROVED** [review]

**Pull request merged**
