### PR TITLE
Flappy bird game

### LINKED ISSUE #408: Flappy bird game using JS
## **Describe the project**
An Endless Game Called Flappy Bird Has A Bird That The User have to manage . The Player Must Prevent The Bird From Hitting Obstacles Like Pipes. Every Time The Bird Moves Through The Pipes, The Score Goes Up By One. When The Bird Hits The The Game Is Over. 

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**
The game would be made by using tech stack html , css and javascript .

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

### PR DESCRIPTION
**Pull request by alisha722**
🛠️ Issue 408
Closes #408 

## Description
An Endless Game Called Flappy Bird Has A Bird That The User have to manage . The Player Must Prevent The Bird From Hitting Obstacles Like Pipes. Every Time The Bird Moves Through The Pipes, The Score Goes Up By One. When The Bird Hits The The Game Is Over.

## Type of change
- [x]  New feature (non-breaking change which adds functionality .
Checklist:
 - [x] I have made this from my own
 - [x] My code follows the style guidelines of this project
 - [x] I have performed a self-review of my own code
 - [x] I have commented my code, particularly in hard-to-understand areas
 - [x] My changes generate no new warnings
 - [x] The title of my pull request is a short description of the requested changes.

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
flappy bird

### CODE REVIEW

**Comment by alisha722** [comment]
I have rectify the errors . Please have a look @zugzwang03

**Review by harshit-paneri — APPROVED** [review]

**Review by abhilipsasahoo03 — APPROVED** [review]
Awesome work @alisha722 looks good to me too. :)

**Comment by alisha722** [comment]
> Awesome work @alisha722 looks good to me too. :)

OKAY . THANKYOU :)

**Review by zugzwang03 — APPROVED** [review]
Great work! @alisha722

**Review by TusharKesarwani — APPROVED** [review]

**Comment by TusharKesarwani** [comment]
Resolve merge conflicts

**Comment by alisha722** [comment]
> Resolve merge conflicts @alisha722

yes done and created new pull request for the same , please have a look . Thankyou.

**Pull request closed without merging**
