### PR TITLE
Improvement In HexCodeGenerator. 

### PR DESCRIPTION
**Pull request by Kumar-Ankit56**
## Refer this attachment for what I have changed.
Screenshot (146)

My Update changes
Screenshot (147)

I have successfully resolved the issue no #301 
please check and assign me.

### CODE REVIEW

**Review by harsh5902 — APPROVED** [review]
done!

**Comment by TusharKesarwani** [comment]
Attach screenshots of improvements you have made
Attach both previous and present project screenshots

**Comment by Kumar-Ankit56** [comment]
> Attach screenshots of improvements you have made Attach both previous and present project screenshots

Allow me a minute I'm just doing.

**Comment by Kumar-Ankit56** [comment]
> I have successfully resolved the issue no #301 please check and assign me.

**Comment by Kumar-Ankit56** [comment]
@TusharKesarwani by mistaken I have closed it,
Please have a look done changes.

**Comment by Kumar-Ankit56** [comment]
@TusharKesarwani please review and merge it.

**Comment by TusharKesarwani** [comment]
Changes are not required

**Pull request closed without merging**
