### PR TITLE
Whiteboard with Color Selection and Saving feature

### PR DESCRIPTION
**Pull request by Dinex-dev**
solving #147

### CODE REVIEW

**Comment by Vanshiii203** [comment]
@Dinex-dev Please add a README.md file in the project with the explanation of your project, tech stack used, and screenshot of the project

**Review by harshit-paneri — CHANGES_REQUESTED** [review]
Please Add readme file and add screenshot also

**Comment by Dinex-dev** [comment]
Ok i will update it

**Review by harshit-paneri — APPROVED** [review]
Great Work @Dinex-dev ✨,
image
but how can I remove this txt "WHITEBOARD"

**Review by Vanshiii203 — APPROVED** [review]

**Comment by Dinex-dev** [comment]
@harshit-paneri Just use clear button at bottom right

**Comment by harshit-paneri** [comment]
> @harshit-paneri Just use clear button at bottom right

okay Great⭐

**Pull request merged**
