### PR TITLE
added unit convertor Closes #1389

### LINKED ISSUE #1389: Add a Simple unit convertor
## **Describe the project**
I want to add a simple unit convertor built using js, html and css

## Issue Type:

- [x] New Project

## **Screenshots**
image

Please assign me this issue

### PR DESCRIPTION
**Pull request by ranjanmangla1**
## 🛠️ Issue (Number)

Closes #1389 

# Description
Added unit convertor written in Html & CSS

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ ] I have made this from my own
- [ ] I have taken help from some online resourses 
- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] The title of my pull request is a short description of the requested changes.

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Review by harshit-paneri — CHANGES_REQUESTED** [review]
Please attach CSS also.
image

**Comment by harshit-paneri** [comment]
share deployed, live link also

**Review by harshit-paneri — APPROVED** [review]
Working💥

**Comment by ranjanmangla1** [comment]
> Working💥

@harshit-paneri HI harshit, it has been a long time this pr has been in ready to merge, when is this gonna merge?

**Pull request merged**
