### PR TITLE
add pagination

### LINKED ISSUE #1674: Add pagination in recipe finder
**Describe the solution you'd like**
Add pagination in recipe finder as it takes too much scrolling when looking for common recipes.

### PR DESCRIPTION
**Pull request by Ashutoshbind15**
## 🛠️ Issue (Number)

Closes #1674 

# Description

Added pagination to the front-end side of the project. It is responsive as well

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] The title of my pull request is a short description of the requested changes.

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
gp1
gp2

### CODE REVIEW

**Review by harshit-paneri — APPROVED** [review]
Pagination is working!!!

**Review by TusharKesarwani — APPROVED** [review]

**Comment by TusharKesarwani** [comment]
Resolve conflicts

**Comment by Ashutoshbind15** [comment]
resolved @TusharKesarwani

**Comment by Ashutoshbind15** [comment]
@TusharKesarwani @harshit-paneri @zugzwang03 Kindly merge this pr, works well, if there is some issue, kindly tell

**Review by TusharKesarwani — APPROVED** [review]

**Pull request merged**
