### PR TITLE
[SSoC 2.0] Sound Equalizer Project Complete

### LINKED ISSUE #1364: [SSoC 2.0] Responsive Sound Equalizer Front End project
## **Describe the project**
- A clear and concise description of the project you are going to add to this repository.
- Sound Equalizer will create using HTML, CSS and JS
- This site will be responsive
- Effective animation and lighting effect will attract the users so much
- Just simple model / clone of sound equalizer
- With 3 functionalities like music, mic, and headphone.
- Using slider will show the details of how much decrement or increment is done

## Issue Type:

- [x] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

### PR DESCRIPTION
**Pull request by Avdhesh-Varshney**
## 🛠️ Issue (Number) - 1364

Closes #1364 

# Description

Please include a summary of the change. Please also include relevant motivation and context. List any dependencies that are required for this change.
- Sound Equalizer is a clone of the sound equalizer system. 
- It is built using HTML, CSS and JavaScript. 
- It is a responsive website that can be viewed on any device.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] The title of my pull request is a short description of the requested changes.

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
Sound_Equalizer

### CODE REVIEW

**Comment by zugzwang03** [comment]
resolve conflicts

**Comment by Avdhesh-Varshney** [comment]
@TusharKesarwani @zugzwang03 Sirs, please again review conflicts resolved and merge this pull request for a successful contribution under SSoC 2.0 program

**Comment by Avdhesh-Varshney** [comment]
@TusharKesarwani Sir, please also review this pr and merge it also

Sir, i also requested to review my other prs also 1413 and 1319

**Comment by zugzwang03** [comment]
still conflicts exist

**Comment by Avdhesh-Varshney** [comment]
@TusharKesarwani @zugzwang03 Sirs, please again review this pr.
Conflicts Resolved !

**Comment by zugzwang03** [comment]
Conflicts still exist.

**Comment by Avdhesh-Varshney** [comment]
@TusharKesarwani @zugzwang03 sir please again review this pr
conflicts have resolved !

**Review by zugzwang03 — APPROVED** [review]

**Review by TusharKesarwani — APPROVED** [review]

**Pull request merged**
