### PR TITLE
Virtual keyboard added

### LINKED ISSUE #231: Virtual Keyboard
A virtual keyboard is an on screen keyboard made using HMTL, CSS and vanila.js that is displayed whenever the user wants to type something on the site, I would like to work upon this, please assign me this project.

### PR DESCRIPTION
**Pull request by suryanshhh28**
Virtual keyboard added
Closes #231 
Please merge this

### CODE REVIEW

**Comment by harshit-paneri** [comment]
Please add images also in this chat

**Comment by suryanshhh28** [comment]
Image URL added in the chat as well as in the readme.md file
image
Please merge this

**Review by Vanshiii203 — APPROVED** [review]
LGTM!

**Review by TusharKesarwani — APPROVED** [review]

**Review by harshit-paneri — COMMENTED** [review]
Amazing

**Comment by AdityaGaur7** [comment]
@TusharKesarwani sir , assign this to me under SSOC 23
It is not fully responsive

Screenshot (230)

**Comment by TusharKesarwani** [comment]
> @TusharKesarwani sir , assign this to me under SSOC 23 It is not fully responsive
> 
> Screenshot (230)

Create a new issue

**Pull request merged**
