### PR TITLE
Added Language Translator Project

### PR DESCRIPTION
**Pull request by Nehaaa3121**
kindly approve my pr

### CODE REVIEW

**Review by Rishikavishnoi — CHANGES_REQUESTED** [review]
@Nehaaa3121 Kindly link the issue which you have resolved and Add Readme.md file

**Comment by Nehaaa3121** [comment]
> @Nehaaa3121 Kindly link the issue which you have resolved and Add Readme.md file

now please check

**Comment by Vanshiii203** [comment]
Hey @Nehaaa3121 This issue is assigned to someone else. You cannot directly raise a PR. You can wait for sometime. If the person fails to complete the task, then it will be assigned to you, and then only this PR will be accepted.

**Comment by Nehaaa3121** [comment]
> Hey @Nehaaa3121 This issue is assigned to someone else. You cannot directly raise a PR. You can wait for sometime. If the person fails to complete the task, then it will be assigned to you, and then only this PR will be accepted.

ok thanks no problem . I have raised the new issue kindly check it.

**Comment by Anubhavgupta14** [comment]
@Nehaaa3121 Kindly Add the Screenshots for better understanding.

**Comment by Nehaaa3121** [comment]
> @Nehaaa3121 Kindly Add the Screenshots for better understanding.

here are the screenshots of my project. this project consists of an audio feature and copy button, one can listen to the quote or can also copy the quote. it also consists of one search button where one can search for new quotes also.

 
Screenshot (162)
Screenshot (164)
Screenshot (166)

**Comment by Nehaaa3121** [comment]
#287 
kindly approve my PR.

**Comment by Nehaaa3121** [comment]
@Vanshiii203 kindly approve my pr
#287  for this issue

**Review by Vanshiii203 — CHANGES_REQUESTED** [review]
Change the title of PR, Remove the files of quote webapp and add a Readme.md file for language translator.

**Comment by Nehaaa3121** [comment]
Screenshot (169)

Language Translator web app using HTML, CSS & JavaScript. it consists of  an audio feature also where users can hear the 
 pronunciation. Users can check the translation of any word or sentence in any language.

#283  Issue number 

#287  pull request

**Comment by Nehaaa3121** [comment]
@Vanshiii203

**Comment by Vanshiii203** [comment]
> @Vanshiii203

create a Readme.md file and in that describe the project ,tech stack used and screenshot of project.

**Comment by Nehaaa3121** [comment]
@Vanshiii203  now check
Screenshot (171)
Screenshot (172)
Screenshot (173)

**Review by Vanshiii203 — CHANGES_REQUESTED** [review]
Add screenshot of project in readme.md file

**Comment by Nehaaa3121** [comment]
@Vanshiii203 done

**Review by Vanshiii203 — APPROVED** [review]

**Comment by TusharKesarwani** [comment]
Screenshot
The translator is not working properly

**Comment by Nehaaa3121** [comment]
> Screenshot The translator is not working properly

Yes it's because i have posted the screenshot.

**Comment by Nehaaa3121** [comment]
> > Screenshot The translator is not working properly
> 
>it is screenshot link not the project link. My project is working properly.

**Comment by TusharKesarwani** [comment]
> 

I'm attaching a screenshot of your project and according to this screenshot your project is not working

**Comment by Nehaaa3121** [comment]
> > 
> 
> I'm attaching a screenshot of your project and according to this screenshot your project is not working

Yes it's because it is a snapshot. If you want then i can share the project link too. You can check that.

**Comment by TusharKesarwani** [comment]
> > > 
> > 
> > 
> > I'm attaching a screenshot of your project and according to this screenshot your project is not working
> 
> Yes it's because it is a snapshot , i have directly added the snapshot for image purpose.If you want then i can share the project link too. You can check that.

I've taken screenshot from your project

**Comment by Nehaaa3121** [comment]
Screenshot (174)
@TusharKesarwani see , its working properly.

**Comment by Nehaaa3121** [comment]
Screenshot (175)

**Review by TusharKesarwani — APPROVED** [review]

**Comment by TusharKesarwani** [comment]
Ok

**Comment by Nehaaa3121** [comment]
> Ok

Thankyou:)

**Pull request merged**
