### PR TITLE
dailyforcast

### LINKED ISSUE #1865: A weather App with enhanced UI
## **Describe the project**
A clear and concise description of the project you are going to add to this repository.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**
I have created a weather App where we can search about the weather condition of your location.
I have used openWeather API to create this APP

## **Screenshots**

- If applicable, add screenshots to help explain your problem.
Screenshot (59)
Screenshot (58)

### PR DESCRIPTION
**Pull request by 0plaze0**
## 🛠️ Issue #1865

Closes #1865

# Description

Please include a summary of the change. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] I have made this from my own
- [x] I have performed a self-review of my own code

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

Screenshot (59)

### CODE REVIEW

**Comment by 0plaze0** [comment]
@zugzwang03 @TusharKesarwani Please Review and merge my project - dailyweatherforcast

**Comment by zugzwang03** [comment]
update your branch

**Comment by 0plaze0** [comment]
@zugzwang03  sorry to bother you again but I am not able to understand what do you mean, isn't my branch already updated

**Comment by zugzwang03** [comment]
image

**Comment by 0plaze0** [comment]
thank you for the help, is it ok now

**Review by TusharKesarwani — CHANGES_REQUESTED** [review]
Not working

**Comment by 0plaze0** [comment]
@TusharKesarwani fixed the issue is it working now

**Review by zugzwang03 — CHANGES_REQUESTED** [review]
not functioning as expected, can you show a demo video?

**Comment by 0plaze0** [comment]
@TusharKesarwani @zugzwang03 fix the bugs check if its run

**Review by TusharKesarwani — APPROVED** [review]

**Pull request merged**
