### PR TITLE
3D Dice by @programmingninjas

### PR DESCRIPTION
**Pull request by programmingninjas**
Issue #90

### CODE REVIEW

**Review by Vanshiii203 — CHANGES_REQUESTED** [review]
Your project is not showing in deploy version
Please fix that

**Comment by MohitNamdev22** [comment]
@programmingninjas we aren't accepting React Projects

**Review by MohitNamdev22 — COMMENTED** [review]
@programmingninjas we aren't accepting React Projects

**Comment by programmingninjas** [comment]
@MohitNamdev22 why was this issue assigned to me then? I mentioned the tech stack used in the project. Never mind will work on something else

**Pull request closed without merging**
