### PR TITLE
Tourism

### LINKED ISSUE #1185: Tourism
**Is your feature request related to a problem? Please describe.**
In the Tourism website the background image of search bar goes behind the navbar which is not appealing

**Describe the solution you'd like**
It would look better if the image is adjusted below the navbar

**Describe alternatives you've considered**
I would like to change it

**Additional context**
Screenshot (47)

@TusharKesarwani Please assign me this issue

### PR DESCRIPTION
**Pull request by suma30**
## 🛠️ Issue (Number)

Closes #1185 

# Description

Updated README file,
Adjusted the image under navigation bar and
Changes in service review section

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [ ] I have taken help from some online resourses 
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by suma30** [comment]
@zugzwang03 Please review my PR for Tourism website

**Review by zugzwang03 — APPROVED** [review]
LGTM

**Comment by suma30** [comment]
@zugzwang03 Could you please merge this pull request

**Comment by zugzwang03** [comment]
@TusharKesarwani kindly look into this

**Review by TusharKesarwani — APPROVED** [review]

**Pull request merged**
