### PR TITLE
[SSoC 2.0] Guess Gender By Name Project Completed

### LINKED ISSUE #1430: [SSoC 2.0] Guess The Gender By Name
## **Describe the project**
A clear and concise description of the project you are going to add to this repository.
- Front end project
- Created using HTML, CSS and JS
- Sending request using API key
- Using API key, data will tell the status of gender of the entered name
- Responsive towards the mobile devices
- Responsive User interface with effective color gradients

## Issue Type:

- [x] New Project

## **Additional context**
Add any other context or screenshots about the project here.

For example, Name -> Lucy as input
FEMALE => as output

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

### PR DESCRIPTION
**Pull request by Avdhesh-Varshney**
## 🛠️ Issue (Number) - 1430

Closes #1430 

# Description

Please include a summary of the change. Please also include relevant motivation and context. List any dependencies that are required for this change.
- This project made by using HTML, CSS and JS
- This project a api url to fetch the probability of that person is male or female
- After converting that probability into percentage, data is shown to the user
- Attractive and smooth user interface with fast functioning will provide a best user experience

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] The title of my pull request is a short description of the requested changes.

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
Guess_The_Gender

### CODE REVIEW

**Comment by Avdhesh-Varshney** [comment]
@TusharKesarwani @zugzwang03 Sirs, please review this pr and merge it into the main branch of this repository for a successful contribution under SSoC 2.0 program

**Review by harshit-paneri — APPROVED** [review]
Great Project 😂😂!!

**Comment by Avdhesh-Varshney** [comment]
> Great Project 😂😂!!

Thanks Sir !

**Review by TusharKesarwani — APPROVED** [review]

**Comment by TusharKesarwani** [comment]
Resolve merge conflicts

**Review by harshit-paneri — APPROVED** [review]
Now it fixed !!

**Comment by Avdhesh-Varshney** [comment]
@TusharKesarwani Sir, please review again this pr. I have resolved the conflicts

**Pull request merged**
