### PR TITLE
Added a Yoga frontend project

### PR DESCRIPTION
**Pull request by sumitkr2000**
Hey, @TusharKesarwani I have added the yoga frontend project where users can register for yoga classes. Please merge my pull request.

### CODE REVIEW

**Comment by TusharKesarwani** [comment]
Please add your project 
Your project is not working

**Comment by TusharKesarwani** [comment]
Your project is not displaying in GitHub
If you are adding your project in a zip file then please don't do this

**Comment by sumitkr2000** [comment]
@TusharKesarwani I am not adding any zip file please check it once again.

**Comment by sumitkr2000** [comment]
@TusharKesarwani Are u able to merge it now?

**Comment by TusharKesarwani** [comment]
> @TusharKesarwani Are u able to merge it now?

You're adding a git repository which is not allowed
Add only the project folder

**Comment by sumitkr2000** [comment]
ok, I am closing this pull request and opening a new one.

**Pull request closed without merging**
