### PR TITLE
Gradient Background Generator

### PR DESCRIPTION
**Pull request by Harikaraja**
issue number : #445

### CODE REVIEW

**Comment by Vanshiii203** [comment]
Hey @Harikaraja this project is already present in the repo. Here is the link to the project https://github.com/TusharKesarwani/Front-End-Projects/tree/main/Projects/Hex%20Code%20Generator
In the project it generates gradient on its own. You can add the color selection option in the same project. 
Would you like to do that??

**Comment by Harikaraja** [comment]
Mam yesterday some mentor assigned it to me mam 😔😔

**Comment by Harikaraja** [comment]
As it was assigned I thought that the project was not in repo and i have
done that project

**Comment by Harikaraja** [comment]
Mam in the existing project i would like to add color button in the
gradient field

**Comment by Vanshiii203** [comment]
@Harikaraja assigned you the issue.

**Comment by Harikaraja** [comment]
Ok mam

**Pull request closed without merging**
