### PR TITLE
Armstrong checker

### LINKED ISSUE #1418: Armstrong checker
**Is your feature request related to a problem? Please describe.**
The background color of the page and the input box is same which is not so attractive.

**Describe the solution you'd like**
If the colors are different it would look better.

**Describe alternatives you've considered**
Changing the background color of the page.

**Additional context**
Screenshot (53)

@TusharKesarwani @zugzwang03 please assign me this issue

### PR DESCRIPTION
**Pull request by suma30**
## 🛠️ Issue (Number)

Closes #1418 

# Description

Changed the background color and also the main heading color for a better look.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [ ] I have taken help from some online resourses 
- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] The title of my pull request is a short description of the requested changes.

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
https://deploy-preview-1504--frontendprojects.netlify.app/projects/armstrongchecker/armstrong

@TusharKesarwani @zugzwang03 @harshit-paneri Please review my PR for the Armstrong checker site

### CODE REVIEW

**Comment by zugzwang03** [comment]
this is already done by PR #1267

**Comment by suma30** [comment]
@TusharKesarwani @zugzwang03 @harshit-paneri  The mentioned PR #1267 has conflicts and is also not merged, so could you please check my PR once again and open it and if possible merge it please

**Comment by suma30** [comment]
@zugzwang03 Could please check and reopen my PR for armstrong checker please

**Review by zugzwang03 — APPROVED** [review]

**Comment by TusharKesarwani** [comment]
Do not create duplicate issue and pull request

**Pull request closed without merging**
