### PR TITLE
LinkedIn Clone 

### PR DESCRIPTION
**Pull request by MridulGupta007**
Closes Issue #149 
Screenshot (225)

### CODE REVIEW

**Review by Rishikavishnoi — CHANGES_REQUESTED** [review]
@MridulGupta007 remove .vscode folder

**Review by Vanshiii203 — CHANGES_REQUESTED** [review]
Remove the .vs code file and add a screenshot of the project to the readme.md file

**Comment by MridulGupta007** [comment]
removed .vscode file, screenshot is added with issue number

**Comment by Vanshiii203** [comment]
> removed .vscode file, screenshot is added with issue number
add a screenshot of the project to the readme.md file

**Comment by MridulGupta007** [comment]
Added screenshot in README.md and removed the table

**Review by Vanshiii203 — APPROVED** [review]

**Comment by TusharKesarwani** [comment]
If you are adding a clone project then you should add a front-end clone not a sign-in page clone

**Pull request closed without merging**
