### PR TITLE
Filters

### PR DESCRIPTION
**Pull request by kuldeepjoshi27**
issue number = #370 

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

Screenshot 2023-01-21 125911
Screenshot 2023-01-21 125932

### CODE REVIEW

**Review by Rishikavishnoi — CHANGES_REQUESTED** [review]
@kuldeepjoshi27 kindly remove the Wikipedia project folder

**Comment by kuldeepjoshi27** [comment]
> @kuldeepjoshi27 kindly remove the Wikipedia project folder

done ma'am

**Review by harshit-paneri — CHANGES_REQUESTED** [review]
image
Please delete Wikipideia and Brick Breaker Game

**Comment by kuldeepjoshi27** [comment]
> image Please delete Wikipideia and Brick Breaker Game

sir actually one of my pull request merge is pending so it is not able to delete.

**Comment by harshit-paneri** [comment]
> > image Please delete Wikipideia and Brick Breaker Game
> 
> sir actually one of my pull request merge is pending so it is not able to delete. and these are just the screenshots of the previos projects.delete options is not working on it.

send me PR no.

**Comment by kuldeepjoshi27** [comment]
> > > image Please delete Wikipideia and Brick Breaker Game
> > 
> > 
> > sir actually one of my pull request merge is pending so it is not able to delete. and these are just the screenshots of the previos projects.delete options is not working on it.
> 
> send me PR no.

aprrove is done but merging and closing is pending thats the reason it is faced by friends too.

**Comment by kuldeepjoshi27** [comment]
Screenshot 2023-01-22 013141

delete button is not responding

**Comment by harshit-paneri** [comment]
ok let I try to merge you'r prev PR

**Comment by kuldeepjoshi27** [comment]
> ok let I try to merge you'r prev PR

okay sir but my previos project is also having a screenshot of brick breaker game and still it approved so i think let you approve and close it

**Comment by harshit-paneri** [comment]
> > ok let I try to merge you'r prev PR
> 
> okay sir but my previos project is also having a screenshot of brick breaker game due to same problem and still it approved so i think let you approve and close it

It may be create conflict when both PR mege , do it's good to go one by one

**Comment by kuldeepjoshi27** [comment]
> > > ok let I try to merge you'r prev PR
> > 
> > 
> > okay sir but my previos project is also having a screenshot of brick breaker game due to same problem and still it approved so i think let you approve and close it
> 
> It may be create conflict when both PR mege , do it's good to go one by one

okay i will take care of it is this request shoul merge or i will create another one.

**Comment by harshit-paneri** [comment]
@kuldeepjoshi27 you can create new brach for new project and send PR, si it's not create any conflict

**Comment by kuldeepjoshi27** [comment]
> @kuldeepjoshi27 you can create new branch for new project and send PR, si it's not create any conflict

okay i have to delete it ?

**Comment by harshit-paneri** [comment]
> > @kuldeepjoshi27 you can create new branch for new project and send PR, si it's not create any conflict
> 
> okay i have to delete it ?

yes

**Comment by kuldeepjoshi27** [comment]
> > > @kuldeepjoshi27 you can create new branch for new project and send PR, si it's not create any conflict
> > 
> > 
> > okay i have to delete it ?
> 
> First create branch and send PR then delete it , if all goes correct
if i create  new one that also facing same problem

**Comment by kuldeepjoshi27** [comment]
my last one was approved with the same issue so i thought it is also approved

**Comment by kuldeepjoshi27** [comment]
how to delete i am not able to delete it.

**Comment by harshit-paneri** [comment]
> my last one was approved with the same issue so i thought it is also approved

ok but now if you work on any issue be sure create new branch then start work on it for safety of merge conflict

**Comment by kuldeepjoshi27** [comment]
> > my last one was approved with the same issue so i thought it is also approved
> 
> ok but now if you work on any issue be sure create new branch then start work on it for safety of merge conflict

sure sir

**Comment by harshit-paneri** [comment]
> how to delete i am not able to delete it.

PR is not deleted it only open or close , if you want to remove it you have to close it

**Comment by kuldeepjoshi27** [comment]
> > how to delete i am not able to delete it.
> 
> PR is not deleted it only open or close , if you want to remove it you have to close it

okay sir

**Pull request closed without merging**
