### PR TITLE
Hospital website

### LINKED ISSUE #579: Website for hospital
## **Describe the project**
I want to design a website frontend for hospital having sections like appointment , doctors available , contact etc. and make it responsive too

## Issue Type:
- [x] New Project

## **Additional context**
I will design it using html , css and javascript only.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

### PR DESCRIPTION
**Pull request by alisha722**
## 🛠️ Issue 579

Closes #579

# Description

I have design a website frontend for hospital having sections like appointment , doctors available , contact etc. and made it responsive too.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my ownes 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] The title of my pull request is a short description of the requested changes.

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
doclab website

### CODE REVIEW

**Review by Vanshiii203 — CHANGES_REQUESTED** [review]
add the screenshot of project in readme.md file

**Comment by alisha722** [comment]
> add the screenshot of project in readme.md file

yes, I have added .

**Review by Vanshiii203 — APPROVED** [review]

**Comment by TusharKesarwani** [comment]
Resolve merge conflicts

**Comment by Vanshiii203** [comment]
@alisha722 Resolve the merge conflicts

**Pull request closed without merging**
