### PR TITLE
Added hover effect to navbar

### PR DESCRIPTION
**Pull request by vibhuti0**
## 🛠️ Issue (Number)1422

Closes #

# Description

Please include a summary of the change. Please also include relevant motivation and context. List any dependencies that are required for this change.

##  Added  Hover Effect to the navbar in the Triposity Project .

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ ] I have made this from my own
- [ ] I have taken help from some online resourses 
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] The title of my pull request is a short description of the requested changes.

# ATTACH SCREEN-SHOTS / DEPLOYMENT [LINK](
image
)

### CODE REVIEW

**Review by harshit-paneri — COMMENTED** [review]
Is your hover effect means , adding href with new page.?

**Comment by vibhuti0** [comment]
> Is your hover effect means , adding href with new page.?

I have added hover effect in the navbar i.e a line appears across the current item as soon as a user hovers over it.

**Review by TusharKesarwani — CHANGES_REQUESTED** [review]
Make the project more attractive

**Comment by vibhuti0** [comment]
> Make the project more attractive

@TusharKesarwani  could you please let me know the changes you  want me to bring?

**Comment by TusharKesarwani** [comment]
> > Make the project more attractive
> 
> @TusharKesarwani could you please let me know the changes you want me to bring?

Work on the UI of the website
Change the look
Make it attractive

**Pull request closed without merging**
