### PR TITLE
Added Random Emoji Generator

### LINKED ISSUE #1380: Adding Random Emoji Generator Website
## **Description**
I want to add Random Emoji generator website made up using HTML ,and beautify using CSS and Javascript.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

### PR DESCRIPTION
**Pull request by dhruti26**
issues #1380

## 🛠️ Issue (Number)

Closes #1380

# Description
This is simple website on hovering over emoji everytime , it will show random emoji which is generated using HTML,CSS and Javascript

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] The title of my pull request is a short description of the requested changes.

# ATTACH SCREEN-SHOTS
image
image

### CODE REVIEW

**Comment by dhruti26** [comment]
@TusharKesarwani @zugzwang03 Please review my PR

**Comment by dhruti26** [comment]
@zugzwang03 Changes Done

**Comment by zugzwang03** [comment]
update branch first

**Comment by dhruti26** [comment]
@zugzwang03 Changes Done

**Review by zugzwang03 — CHANGES_REQUESTED** [review]
add readme file

**Comment by dhruti26** [comment]
@zugzwang03 Added README.md file

**Comment by dhruti26** [comment]
@zugzwang03 Please review my changes

**Review by TusharKesarwani — APPROVED** [review]

**Pull request merged**
