### PR TITLE
Postman Clone

### PR DESCRIPTION
**Pull request by Harikaraja**
## 🛠️ Issue (Number) : #565 

Closes #

# Description

Post Master clone is similar to postman API platform where we can enter the URL and get the information in the format specified by the user.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [X] I have made this from my own
- [ ] I have taken help from some online resourses 
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] The title of my pull request is a short description of the requested changes.

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
Screenshot (334)

Screenshot (335)

### CODE REVIEW

**Review by Rishikavishnoi — APPROVED** [review]
@Harikaraja LGTM 👍

**Comment by Harikaraja** [comment]
Sir but it was not labelled as approved ready to merge , are there any
changes to be done

**Comment by Harikaraja** [comment]
Sir i have mentioned

**Comment by Harikaraja** [comment]
Sir it is mentioned yesterday that my pr has already been accepted

**Comment by Harikaraja** [comment]
sir added the issue number .please check and approve

**Review by Arun9739 — APPROVED** [review]

**Review by TusharKesarwani — APPROVED** [review]

**Pull request merged**
