### PR TITLE
Added e-commerce landing page

### PR DESCRIPTION
**Pull request by sumitkr2000**
Hey, I have added the e-commerce landing page using HTML and CSS. Please review my PR and merge it. Thank you!

Issue no #227

### CODE REVIEW

**Review by Vanshiii203 — CHANGES_REQUESTED** [review]
Add a Readme.md file and link the issue with the PR

**Comment by sumitkr2000** [comment]
Done mam :) @Vanshiii203

**Comment by Vanshiii203** [comment]
In readme.md file you have to explain your project, the tech stack used, and a screenshot of your project
and you have to link the issue in the comment of the PR(by using #issuenumber) and not in readme

**Comment by sumitkr2000** [comment]
Ab check kijiye @Vanshiii203 ji :)

**Comment by sumitkr2000** [comment]
Please merge my pr @TusharKesarwani

**Comment by sumitkr2000** [comment]
Please merge my pr @TusharKesarwani

**Review by Vanshiii203 — APPROVED** [review]

**Review by TusharKesarwani — APPROVED** [review]

**Pull request merged**
