### PR TITLE
Redesign a front-end food ordering website

### LINKED ISSUE #177: Redesign a front-end food ordering website
Wanted to add some new files and make the site responsive.
https://github.com/TusharKesarwani/Front-End-Projects/tree/main/Projects/Food%20Ordering%20website

Changes :
1. Improving the UI
2. Adding a JS file for better functionality
3. Adding a readme.md file

### PR DESCRIPTION
**Pull request by ARCHITABHATTAD**
## 🛠️ Issue (Number)
Closes #177

# Description

Please include a summary of the change. Please also include relevant motivation and context. List any dependencies that are required for this change.
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# Checklist:
- [x] I have made this from my own
- [ ] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] The title of my pull request is a short description of the requested changes.

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
Screenshot 2023-02-01 225208
Screenshot 2023-02-01 225300
Screenshot 2023-02-01 225320
Screenshot 2023-02-01 225421

### CODE REVIEW

**Comment by ARCHITABHATTAD** [comment]
@TusharKesarwani please check and merge the pr....have raised it as instructed.

**Review by Arun9739 — CHANGES_REQUESTED** [review]
Rename the 'mini' folder to 'img', as it contains the images.

**Review by Vanshiii203 — APPROVED** [review]

**Comment by TusharKesarwani** [comment]
Make it responsive

**Review by Arun9739 — APPROVED** [review]

**Comment by TusharKesarwani** [comment]
Project is already present in the repo
https://github.com/TusharKesarwani/Front-End-Projects/tree/main/Projects/Food%20Ordering%20website

**Comment by ARCHITABHATTAD** [comment]
@TusharKesarwani sir I have contributed the earlier project as well....... that is why named This issue as redesign of the earlier project.....and already had an approval from you before going ahead with the issue.

**Comment by TusharKesarwani** [comment]
Screenshot
Make it responsive

**Review by siddhi-244 — APPROVED** [review]

**Pull request closed without merging**
