### PR TITLE
Day Planner Website

### PR DESCRIPTION
**Pull request by Harshit-Raj-14**
Used HTML, CSS AND JavaScript to make a Day Planner Website.

**Description** - This websites is able to update to real time using moment.js. Data is also stored in local storage. Easy to follow design and setup. Also, the head line moves down as time passes by and the task is completed fort he day.

**Objective** - the day planner helps you to easily record and structure your task for the day.

Screenshot (50)

### CODE REVIEW

**Comment by Vanshiii203** [comment]
@Harshit-Raj-14 Please link the issue which you have resolved!

**Review by Vanshiii203 — CHANGES_REQUESTED** [review]
@Harshit-Raj-14 Please link the issue which you have resolved!

**Comment by Harshit-Raj-14** [comment]
> @Harshit-Raj-14 Please link the issue which you have resolved!

@Vanshiii203 I have directly uploaded the project by making a PR. I have made sure there were no day planners already existing issue or an already existing project in repo.

**Comment by Harshit-Raj-14** [comment]
@Vanshiii203 Ok I have raised an issue for this project as well. This project  is for the issue #161 
I hope it gets merged now.

**Review by Vanshiii203 — APPROVED** [review]
LGTM!

**Comment by Vanshiii203** [comment]
@Harshit-Raj-14 From now on, you should raise the issue first before making PRs.

**Comment by Vanshiii203** [comment]
@Harshit-Raj-14 Please add a README.md file in the project with the explanation of your project, tech stack used, and screenshot of the project

**Comment by Harshit-Raj-14** [comment]
@Vanshiii203 I have added a readme file with a description, tech stack used, and a screenshot of the website. Please take a look. I hope it can get merged now. 
Thank you.

**Review by TusharKesarwani — APPROVED** [review]

**Pull request merged**
