### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by noobcoder007-exe**
This is an Enhancement on the Audio-Text-Converter project where the primary use of the software is to convert the input voice into text.

This project is made under SSoC'23.

Original features:
    converts Voice to text.
Newly Added Features
    copies the converted text onto the clipboard for reusable purposes

### CODE REVIEW

**Comment by zugzwang03** [comment]
issue number?

**Comment by noobcoder007-exe** [comment]
isuue number is #1192

**Comment by zugzwang03** [comment]
update your branch first

**Comment by noobcoder007-exe** [comment]
what exactly do i have to do to update the main branch

**Pull request closed without merging**
