### PR TITLE
added calendar

### PR DESCRIPTION
**Pull request by khushigarg1**
issue number #145

### CODE REVIEW

**Review by harshit-paneri — COMMENTED** [review]
Calender Project Approved✨

**Review by Rishikavishnoi — CHANGES_REQUESTED** [review]
@khushigarg1 it looking good but also resolve merge conflict

**Comment by khushigarg1** [comment]
> @khushigarg1 it looking good but also resolve merge conflict

there is no option to merge or resolve conflicts. Can you tell me from where i can do that ?

**Review by Vanshiii203 — CHANGES_REQUESTED** [review]
please delete the readme copy.md file

**Comment by khushigarg1** [comment]
> please delete the readme copy.md file

I deleted but idkk why its happening if i am deleting readmecopy.md then there is showing prime checker readme automatically.

**Review by harshit-paneri — APPROVED** [review]

**Comment by Vanshiii203** [comment]
> > please delete the readme copy.md file
> 
> I deleted but idkk why its happening if i am deleting readmecopy.md then there is showing prime checker readme automatically.

delete the prime project folder now

**Comment by khushigarg1** [comment]
> > > please delete the readme copy.md file
> > 
> > 
> > I deleted but idkk why its happening if i am deleting readmecopy.md then there is showing prime checker readme automatically.
> 
> delete the prime project folder now

I am not able to delete that folder.

**Pull request closed without merging**
