### PR TITLE
updated air-quality page

### PR DESCRIPTION
**Pull request by shivang-16**
updated the UI of the air quality project ..and also I made it responsive..

Screenshot 2023-06-09 223801
Screenshot 2023-06-09 223848

### CODE REVIEW

**Comment by harshit-paneri** [comment]
Issue number ?

**Comment by shivang-16** [comment]
Refer to issue #1121 
I have fixes the following issues-->
1> Addes Polution control tips button and card 
2> Close button is not working in Modal card ...I have fixed this issue
3> Improve the UI OF the page by adding shadaw to boxes 
4> Format the whole Front-End-Projexts ducuemnt by using prettier
Screenshot 2023-06-10 191423
Screenshot 2023-06-10 191435
Screenshot 2023-06-10 191445
Screenshot 2023-06-10 191521

**Comment by harshit-paneri** [comment]
Issues is not assign to you

**Comment by harshit-paneri** [comment]
> Please assign it to me ....i have already fix all the issues

you can not send PR of issue which is created by other , take permission from them.

**Pull request closed without merging**
