### PR TITLE
Memory Game (4 Tiles)

### PR DESCRIPTION
**Pull request by Anmol-Baranwal**
Simple JavaScript game in which we must repeat the previous and current sequences to advance to the next level.

- I made this while learning JavaScript in my early phase, and it was not in the repository. So, I made a PR.

- It is different from #113 

Also, I am not part of SWOC so it is up to you whether you want to add appropriate tags.

### CODE REVIEW

**Comment by Anmol-Baranwal** [comment]
> @Anmol-Baranwal kindly add a README file with all the details of your project, i.e., functionalities, tech stack, etc. Also add demo screenshots and video of your project into it. It'll help us know how exactly the game works.

Okay, I will make appropriate changes.

**Comment by Anmol-Baranwal** [comment]
Do let me know if you want me to do any further changes.

**Review by abhilipsasahoo03 — CHANGES_REQUESTED** [review]
Sure just one last thing, pls add reference screenshot/demo video in the PR for us to take a look.

**Comment by Anmol-Baranwal** [comment]
> Sure just one last thing, pls add reference screenshot/demo video in the PR for us to take a look.

I have already added screenshots of the interface. What do you want me to add?

**Comment by abhilipsasahoo03** [comment]
> > Sure just one last thing, pls add reference screenshot/demo video in the PR for us to take a look.
> 
> I have already added screenshots of the interface. What do you want me to add?

Demo video?

**Comment by abhilipsasahoo03** [comment]
Okay so I went through screenshots and it looks good to me. Honestly, for static websites it's okay to add just the screenshots, but for games, it is recommended to add demo videos (just a good practice). Anyway, I'm approving. :)

**Review by abhilipsasahoo03 — APPROVED** [review]
LGTM

**Comment by TusharKesarwani** [comment]
Add rules of the game in the website

**Comment by Anmol-Baranwal** [comment]
> Add rules of the game in the website

It's a simple game, any human would take 5s to understand without any explanation. 
Is it really mandatory to add simple rules? (I have already added in the markdown readme.md)

**Comment by TusharKesarwani** [comment]
> > Add rules of the game in the website
> 
> It's a simple game, any human would take 5s to understand without any explanation. Is it really mandatory to add simple rules? (I have already added in the markdown readme.md)
> 
> Note: I am not doing this contribution under SWOC so feel free to remove the label. I just thought to contribute.

Yes, it is mandatory to add rules

**Comment by Anmol-Baranwal** [comment]
@TusharKesarwani 

As per conversation, I have added the instructions and updated the readme accordingly.

**Review by TusharKesarwani — APPROVED** [review]

**Pull request merged**
