### PR TITLE
Pig game has been added successfully

### PR DESCRIPTION
**Pull request by abhijeet-26**

### CODE REVIEW

**Comment by abhilipsasahoo03** [comment]
@abhijeet-26 please add a proper description in your PR and link the issue it resolves. Also, kindly add a demo video to your PR as well to give maintainers a brief idea on how exactly your project works.

**Review by Vanshiii203 — CHANGES_REQUESTED** [review]
Please add a README.md file in the project with the explanation of your project, tech stack used, and screenshot of the project

**Comment by abhijeet-26** [comment]
Okay. Thanks for your feedback.

**Comment by abhijeet-26** [comment]
@Vanshiii203 please check now and let me know

**Review by Vanshiii203 — APPROVED** [review]
Good work! But from next time try to keep all the images in a single folder.

**Comment by abhijeet-26** [comment]
@Vanshiii203  yes sure. Thank you 🙏

**Review by TusharKesarwani — APPROVED** [review]

**Pull request merged**
