### PR TITLE
Payment Portal added to SARGAM, a music streaming website: Closes #1640

### LINKED ISSUE #1640: SARGAM, a music streaming website
**## **Describe the project****

SARGAM is a front-end developed music streaming website with different Log In, Sign Up page and all the navigation bar links are functional.

## Issue Type:

- [x] New Project

## **Screenshots**

Screenshot 2023-07-08 095702
Screenshot 2023-07-08 095723
Screenshot 2023-07-08 095735
Screenshot 2023-07-08 095758

### PR DESCRIPTION
**Pull request by SagarG2003**
## 🛠️ Issue (Number)

Closes #1640 

# Description

I had added a payment gateway portal to my website which will be redirected on signing up on the website

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] The title of my pull request is a short description of the requested changes.

# ATTACH SCREEN-SHOTS 

Screenshot 2023-07-12 010036

### CODE REVIEW

**Comment by SagarG2003** [comment]
@TusharKesarwani @zugzwang03 Payment Gateway is added to the website which is developed by me stated to issue #1640. Please add this project to the repo.

**Comment by SagarG2003** [comment]
@TusharKesarwani @zugzwang03 I had added a payment gateway portal to my website. Please review it and merge it to the main repo. Closes #1640.

**Comment by SagarG2003** [comment]
Under SSOC 2.0

**Review by zugzwang03 — CHANGES_REQUESTED** [review]
add readme

**Comment by SagarG2003** [comment]
@zugzwang03 Readme File added

**Review by zugzwang03 — APPROVED** [review]

**Review by TusharKesarwani — CHANGES_REQUESTED** [review]
Make changes in one project only

**Comment by SagarG2003** [comment]
I had added changes to this project only.

**Comment by TusharKesarwani** [comment]
> I had added changes to this project only.

You had made changes in four projects folder
Make changes in one project folder at a time

**Pull request closed without merging**
