### PR TITLE
Crypto DashBoard

### LINKED ISSUE #243: Crypto Dashboard
Shows the current value of various tokens in real time

### PR DESCRIPTION
**Pull request by MridulGupta007**
## 🛠️ Issue (Number)
#243 

Closes #243 

# Description
Crypto Dashboard shows the price of various tokens in real time
Please include a summary of the change. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ ] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] The title of my pull request is a short description of the requested changes.

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
Screenshot (228)
Screenshot (227)
Screenshot (226)

### CODE REVIEW

**Review by harshit-paneri — CHANGES_REQUESTED** [review]
image

Image is not loaded and page is not responsive

**Comment by MridulGupta007** [comment]
logo is fixed, and page is responsive

**Comment by MridulGupta007** [comment]
Screenshot (233)
Screenshot (232)

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
Please make the readme more descriptive,  rather than writing the issue number.

**Review by harshit-paneri — APPROVED** [review]

**Review by siddhi-244 — APPROVED** [review]

**Review by TusharKesarwani — APPROVED** [review]

**Pull request merged**
