### PR TITLE
Music player javascript

### PR DESCRIPTION
**Pull request by papri24majumder**
#45 
Description: Created a music player using HTML, CSS, and JavaScript. 
Screenshot
image2

### CODE REVIEW

**Comment by papri24majumder** [comment]
@harshit-paneri do I need to do anything?

**Review by Vanshiii203 — CHANGES_REQUESTED** [review]
Please add a README.md file in the project with the explanation of your project, tech stack used, and screenshot of the project

**Comment by papri24majumder** [comment]
@Vanshiii203 I have added a readme.md file, kindly check.

**Review by Vanshiii203 — APPROVED** [review]
LGTM!

**Review by harshit-paneri — APPROVED** [review]

**Review by TusharKesarwani — APPROVED** [review]

**Pull request merged**
