### PR TITLE
Redesign a front-end food ordering website

### LINKED ISSUE #177: Redesign a front-end food ordering website
Wanted to add some new files and make the site responsive.
https://github.com/TusharKesarwani/Front-End-Projects/tree/main/Projects/Food%20Ordering%20website

Changes :
1. Improving the UI
2. Adding a JS file for better functionality
3. Adding a readme.md file

### PR DESCRIPTION
**Pull request by ARCHITABHATTAD**
## 🛠️ Issue (Number)
Closes #177

# Description
Changes :
1.Improving the UI
2.Adding a JS file for better functionality
3.Adding more functionality

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# Checklist:
- [x] I have made this from my own
- [] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] The title of my pull request is a short description of the requested changes.

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
Screenshot 2023-02-01 225208
Screenshot 2023-02-01 225229
Screenshot 2023-02-01 225300
Screenshot 2023-02-01 225320
Screenshot 2023-02-01 225421

### CODE REVIEW

**Comment by ARCHITABHATTAD** [comment]
@Vanshiii203 and @TusharKesarwani please review my PR....and approve it for merge

**Review by LiQuiD-404 — CHANGES_REQUESTED** [review]
@ARCHITABHATTAD Add a Readme.md file for your project.

**Comment by ARCHITABHATTAD** [comment]
@LiQuiD-404 Done with the required changes

**Review by LiQuiD-404 — APPROVED** [review]
Good work. LGTM ✨

**Review by harshit-paneri — APPROVED** [review]

**Review by Vanshiii203 — CHANGES_REQUESTED** [review]
make it responsive.

**Comment by ARCHITABHATTAD** [comment]
https://user-images.githubusercontent.com/87604491/216803049-7dfbbcf6-32a0-45c8-93db-e2b205f8fe57.mp4

**Comment by ARCHITABHATTAD** [comment]
@Vanshiii203 please check for the required changes....and approve the pr!

**Review by harsh5902 — APPROVED** [review]
good!

**Comment by harsh5902** [comment]
you can still improve its user interface using bootstrap and css work on it.

**Review by Vanshiii203 — CHANGES_REQUESTED** [review]
The navbar is not responsive(on click functionality is not working) and there is a horizontal overflow

**Comment by ARCHITABHATTAD** [comment]
https://user-images.githubusercontent.com/87604491/218244297-beeb4603-052c-4898-aa66-1d0d8f9a0e9d.mp4

@Vanshiii203 the navbar is completely responsive.....please check once

**Review by Vanshiii203 — CHANGES_REQUESTED** [review]
https://user-images.githubusercontent.com/94471189/218294967-f33268ab-791f-4041-bd69-196367f7433e.mp4

**Comment by ARCHITABHATTAD** [comment]
@Vanshiii203 you are checking wrong project.....please go through it once....

**Comment by Vanshiii203** [comment]
@ARCHITABHATTAD Your changes are not reflected in the deploy preview

**Comment by ARCHITABHATTAD** [comment]
@Vanshiii203 what should I do then

**Comment by TusharKesarwani** [comment]
> @Vanshiii203 what should I do then

maybe you are making changes to a different branch
Make a new branch and then add your latest project and then make a fresh PR

**Pull request closed without merging**
