### PR TITLE
Restaurant Website

### LINKED ISSUE #489: Restaurant website
## **Describe the project**
A responsive Restaurant website made using HTML, CSS and JavaScript

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Additional context**
Please assign this to me
## **Screenshots**

ss1
ss2

### PR DESCRIPTION
**Pull request by ankushroy25**
## 🛠️ Issue 489

Closes #489 

# Description

A frontend responsive restaurant website made using HTML, CSS, Bootstrap, JavaScript

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] The title of my pull request is a short description of the requested changes.

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
ss1
ss3

### CODE REVIEW

**Comment by harsh5902** [comment]
What features does this website have??

**Comment by harsh5902** [comment]
There are lot of files present here as you have installed bootstrap locally for this project, I would recommend to bootstrap CDN instead of this.

**Review by harsh5902 — CHANGES_REQUESTED** [review]
use bootstrap CDN

**Comment by ankushroy25** [comment]
Removed the new feature checkbox and updated the requested bootstrap cdn changes.

**Review by harsh5902 — APPROVED** [review]
ok good

**Review by Arun9739 — APPROVED** [review]
Good website !

**Review by TusharKesarwani — APPROVED** [review]

**Pull request merged**
