### PR TITLE
added music player 

### LINKED ISSUE #480: Music Player
## **Describe the project**
As streaming is increasingly being adopted by users, online media players have become essential for consuming media on the internet. Music players allow one to enjoy music in any browser and supports a lot of the features of an offline music player.
I will be creating a music player with a clean user interface that can be used to play music in the browser. I will also implement features like seeking and volume control. HTML has several methods in the HTMLMediaElement interface that can be used to play audio files and control its playback without using any other library.
I will start by creating the HTML layout first that defines the structure of the player, make it look good by styling using CSS and then write the player logic for all the functions in JavaScript.

## Issue Type
- [x] New Project
 
Please assign me this project so that I start working on it

### PR DESCRIPTION
**Pull request by ayushi-ras**
## 🛠️ Issue (Number)

Closes #480 

# Description

As streaming is increasingly being adopted by users, online media players have become essential for consuming media on the internet. Music players allow one to enjoy music in any browser and supports a lot of the features of an offline music player.
I will be creating a music player with a clean user interface that can be used to play music in the browser. I will also implement features like seeking and volume control. HTML has several methods in the HTMLMediaElement interface that can be used to play audio files and control its playback without using any other library.
I will start by creating the HTML layout first that defines the structure of the player, make it look good by styling using CSS and then write the player logic for all the functions in JavaScript.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
Screenshot 2023-01-29 22 41 04
- [x] The title of my pull request is a short description of the requested changes.

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Review by Rishikavishnoi — CHANGES_REQUESTED** [review]
@ayushi-ras add README.md file

**Comment by ayushi-ras** [comment]
@Rishikavishnoi added the readme file ma'am

**Review by Rishikavishnoi — APPROVED** [review]
LGTM...!

**Comment by ayushi-ras** [comment]
Thank you ma'am

**Review by TusharKesarwani — APPROVED** [review]

**Pull request merged**
