### PR TITLE
Added a Responsive Gym Landing Page

### PR DESCRIPTION
**Pull request by AnkitaSikdar005**
## 🛠️ Issue (Number)

Closes #1942 

# Description

It is a gym landing page made using HTML and CSS.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] The title of my pull request is a short description of the requested changes.

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
https://ankitasikdar005.github.io/Gym-Landing-Page/

### CODE REVIEW

**Comment by AnkitaSikdar005** [comment]
@TusharKesarwani , Sir, I have made all the necessary changes .

**Comment by TusharKesarwani** [comment]
Where is the landing page?

**Comment by AnkitaSikdar005** [comment]
image
image
image
@TusharKesarwani Here are the  screenshots of the HTML and CSS codes given in this pr

**Comment by TusharKesarwani** [comment]
CSS is not working properly in your project
Work and improve the UI of the project

**Pull request closed without merging**
