### PR TITLE
Added my project files

### LINKED ISSUE #74: Movie Search App

### PR DESCRIPTION
**Pull request by money8203**
## 🛠️ Issue (Number)

Closes #74

# Description

The current purpose of this project is to provide you with the title and poster of the movie you want to search

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] The title of my pull request is a short description of the requested changes.

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
Screenshot (153)

### CODE REVIEW

**Review by harshit-paneri — CHANGES_REQUESTED** [review]
Website is not **responsive**
image

**Review by harshit-paneri — APPROVED** [review]

**Review by harshit-paneri — CHANGES_REQUESTED** [review]
CSS is still not correct please check it's preview

**Comment by money8203** [comment]
Can you tell me what's the bug ?

**Review by Vanshiii203 — CHANGES_REQUESTED** [review]
image
image
the alignment is not proper and also the website is not responsive

**Pull request closed without merging**
