### PR TITLE
Grocery selling website landing page

### PR DESCRIPTION
**Pull request by Sreehitha2003**

### CODE REVIEW

**Comment by Sreehitha2003** [comment]
> @Sreehitha2003 Add Readme file and link with issue which you resolve ...!

#327

**Review by harshit-paneri — COMMENTED** [review]
Add screenshot also

**Comment by Sreehitha2003** [comment]
> Add screenshot also

I already did

**Comment by Sreehitha2003** [comment]
> Have you not linked the product page to home page??

NO should I?

**Comment by Sreehitha2003** [comment]
> Have you not linked the product page to home page??

I did the changes

**Review by Vanshiii203 — APPROVED** [review]
LGTM

**Comment by TusharKesarwani** [comment]
The E-commerce project is already added by someone

**Pull request closed without merging**
